"""Create a deterministic ten-document token-light factory pilot."""
from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import yaml


ROOT = Path(__file__).resolve().parent / "pilot_project"
TEMPLATES = ROOT / "templates"
ASSETS = TEMPLATES / "assets"

SECTION_TITLES = [
    "Identity and node/region", "Why this BGC was selected", "Boundary and assembly status",
    "Gene-by-gene interpretation", "Core biosynthetic logic", "Tailoring and maturation logic",
    "Transport, resistance, and regulation", "Comparator/KCB interpretation", "Alternative hypotheses",
    "Fragmentation and co-capture risks", "Product-family interpretation", "Bee/microbe ecological interpretation",
    "Antibacterial/antifungal relevance", "What cannot be claimed", "Missing evidence",
    "BLASTP/HMMER next steps", "LC-MS / fermentation implications", "Figure/locus-map notes",
    "Final Mode B judgement", "Next actions", "Precursor mass ladder", "RiPP database search",
    "Heterologous expression", "Scaffold novelty score", "Genome neighbourhood", "OSMAC protocol",
    "Self-resistance assessment", "Evidence provenance ledger", "Cross-cluster interactions",
    "Experimental decision tree", "Region CDS census", "Assembly-line inventory",
    "Module programming readout", "Initiation & release logic", "Protocluster decomposition",
    "Boundary status + overmerge/locus-splitting adjudication (merged)", "Partner & accessory proteins",
    "Co-located resistance & efflux", "Cross-strain sequence identity", "BiG-SCAPE family / cohort placement",
    "Protein / domain phylogeny", "Horizontal transfer evidence", "Split-pathway / cross-contig (RG-GMCI)",
    "Within-cohort prevalence & tier", "Supervisor / university cohort comparison",
    "Type / reference strain comparison", "Host-matched unrelated reference",
    "Cross-cohort synthesis & claim ceiling",
]


def make_assets() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(7.2, 3.1), dpi=160)
    labels = ["Inventory", "Domains", "Comparators", "Context"]
    values = [1.0, 0.78, 0.54, 0.68]
    ax.barh(labels[::-1], values[::-1], color=["#0B8793", "#E6A623", "#0B8793", "#0B8793"][::-1])
    ax.set_xlim(0, 1.05)
    ax.set_xlabel("Synthetic evidence-state completeness")
    ax.set_title("Evidence Streams Remain Separate", loc="left", weight="bold", color="#082A45")
    ax.spines[["top", "right", "left"]].set_visible(False)
    ax.grid(axis="x", color="#DCE4E7")
    fig.tight_layout()
    fig.savefig(ASSETS / "evidence.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7.2, 3.5), dpi=160)
    ax.axis("off")
    for x1, y1, x2, y2 in [
        (0.7, 3.6, 2.0, 3.6), (0.7, 2.6, 0.7, 3.6), (2.0, 3.6, 5.6, 4.1),
        (2.0, 3.6, 5.6, 3.1), (0.7, 2.6, 5.6, 2.1), (0.7, 2.6, 5.6, 1.1),
    ]:
        ax.plot([x1, x2], [y1, y2], color="#0B8793", linewidth=2)
    for label, y in [("Template_A", 4.1), ("Template_B", 3.1), ("Template_C", 2.1), ("Outgroup", 1.1)]:
        ax.text(5.75, y, label, va="center", fontsize=9)
    ax.text(2.1, 3.75, "97", color="#D45B42", fontsize=8)
    ax.set_xlim(0.2, 7.2)
    ax.set_ylim(0.5, 4.6)
    ax.set_title("Synthetic Tree Layout", loc="left", weight="bold", color="#082A45")
    fig.tight_layout()
    fig.savefig(ASSETS / "tree.png", bbox_inches="tight", facecolor="white")
    plt.close(fig)


def write_templates() -> None:
    TEMPLATES.mkdir(parents=True, exist_ok=True)
    (TEMPLATES / "guide.md").write_text(
        """# {{topic}}

> [LEAD] The short version
> {{lead}}

## Three steps

1. Inspect the source package and manifest.
2. Separate deterministic extraction from interpretation.
3. Preserve the claim ceiling in every shared output.

<!-- sapote:table id=quick_choices layout=portrait repeat_header=true widths=2,4 -->
| Choice | When to use it |
|---|---|
| Core | Deterministic extraction and package validation |
| Figures | Scientific plots and captioned reports |
| Documents | Governed Word and PDF output |

## Next action

{{next_action}}
""",
        encoding="utf-8",
    )
    (TEMPLATES / "report.md").write_text(
        """# {{topic}}

This synthetic report tests a reusable figure-rich body without repeating document metadata.

> [CAUTION] Demonstration only
> Values are fabricated and support no biological conclusion.

## Evidence summary

<!-- sapote:figure id=evidence layout=full -->
![Four synthetic evidence-state bars](assets/evidence.png)
**Caption:** {{caption}}
**Methods:** Fixed synthetic values rendered locally for document-layout testing.
**Source:** Token-light pilot fixture generated by build_pilot_inputs.py.

## Reader decision

{{decision}}
""",
        encoding="utf-8",
    )
    (TEMPLATES / "tree_report.md").write_text(
        """# Tree Presentation Pilot

The tree is treated as a governed scientific figure rather than an uncaptioned decoration.

<!-- sapote:figure id=tree layout=full -->
![Synthetic four-tip branching diagram](assets/tree.png)
**Caption:** Synthetic topology used only to test terminal labels, support text, and scale-aware placement.
**Methods:** Hand-constructed coordinates; no sequences, alignment, model, or inference were used.
**Source:** Token-light pilot fixture generated by build_pilot_inputs.py.

> [HOLD] Interpretation withheld
> A real tree requires an exact sequence roster, alignment, trimming, model, rooting, support definition, and source manifest.
""",
        encoding="utf-8",
    )

    special = {
        1: "{{exact_locus}} is the complete synthetic identity. The alias alone is not sufficient.",
        2: "This fixture tests reuse of one Mode B body across exact loci without transferring biological claims.",
        3: "No GBK backs the synthetic interval; boundary and assembly states remain SOURCE_UNBOUND.",
        4: """<!-- sapote:table id=gene_matrix layout=landscape repeat_header=true widths=1.1,1.2,1.7,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2 -->
| Gene | SHA prefix | Proposed role | nr subject | nr identity | nr positives | ClusteredNR subject | CNR identity | CNR positives | Swiss-Prot subject | SP identity |
|---|---|---|---|---|---|---|---|---|---|---|
| {{core_gene}} | a1b2c3d4 | synthetic core candidate | UNBOUND | n/a | n/a | UNRETURNED | n/a | n/a | NOT_SCANNED | n/a |
| {{tailoring_gene}} | b2c3d4e5 | synthetic tailoring candidate | UNBOUND | n/a | n/a | UNRETURNED | n/a | n/a | NOT_SCANNED | n/a |
| {{transport_gene}} | c3d4e5f6 | transporter-family candidate | UNBOUND | n/a | n/a | UNRETURNED | n/a | n/a | NOT_SCANNED | n/a |""",
        5: "{{core_gene}} could act before {{tailoring_gene}}, but no exact domains or substrates are bound; the competing primary-metabolism interpretation remains open.",
        6: "{{tailoring_gene}} is a gene-oriented maturation hypothesis only. Order and substrate require exact domain and biochemical evidence.",
        7: "{{transport_gene}} has no resistance-specific local evidence. Transport, export, and self-resistance remain distinct unresolved hypotheses.",
        20: "No A-domain target is assigned because no staged structured evidence localizes an AMP-binding or adenylation domain.",
        27: "No self-resistance gene is assigned. {{transport_gene}} cannot carry that conclusion without resistance-specific local evidence.",
        29: "RG-GMCI, BiG-SCAPE, ClusterBlast, assembly-link, and exact local comparisons are NOT_STAGED; no interaction conclusion follows.",
        45: "The exact {{core_gene}}, {{tailoring_gene}}, and {{transport_gene}} queries have no staged cohort scans.",
        46: "The exact {{core_gene}}, {{tailoring_gene}}, and {{transport_gene}} queries have no staged type/reference scans.",
        48: "This reusable synthetic body establishes document structure only. It does not establish a complete locus, product, production, activity, resistance, ecology, novelty, or linkage.",
    }
    sections = []
    for number, title in enumerate(SECTION_TITLES, start=1):
        text = special.get(number, f"Section {number} remains a synthetic typed hold until exact staged evidence supports a locus-specific interpretation.")
        sections.append(f"## §{number} {title}\n\n{text}")
    (TEMPLATES / "modeb.md").write_text("\n\n".join(sections) + "\n", encoding="utf-8")


def write_manifest() -> None:
    documents = [
        {
            "id": "guide_quickstart", "source": "templates/guide.md", "document_type": "human_guide",
            "title": "Five-Minute Quickstart", "subtitle": "Shared defaults, one short body template",
            "variables": {"topic": "Start With the Manifest", "lead": "Validate the sealed evidence handoff before interpretation.", "next_action": "Open the package manifest and gate report."},
        },
        {
            "id": "guide_claims", "source": "templates/guide.md", "document_type": "human_guide",
            "title": "Claim Ceilings at a Glance", "subtitle": "A second guide from the same body",
            "variables": {"topic": "Keep Capacity Separate From Production", "lead": "A clean software gate is not a biological result.", "next_action": "Record unsupported conclusions as typed holds."},
        },
        {
            "id": "guide_install", "source": "templates/guide.md", "document_type": "human_guide",
            "title": "Installation Choices", "subtitle": "Core, figures, and documents profiles",
            "variables": {"topic": "Choose Only the Add-ons You Need", "lead": "The documents profile adds governed Word and PDF output.", "next_action": "Verify platform-matched wheels before an offline run."},
        },
        {
            "id": "report_evidence", "source": "templates/report.md", "document_type": "analysis_report",
            "title": "Evidence-State Report", "subtitle": "Synthetic figure-rich batch document",
            "variables": {"topic": "Evidence Streams", "caption": "Four evidence streams remain visually and semantically separate.", "decision": "Inspect each source channel before drawing a conclusion."},
        },
        {
            "id": "report_comparison", "source": "templates/report.md", "document_type": "analysis_report",
            "title": "Comparison-State Report", "subtitle": "Template reuse without prose duplication",
            "variables": {"topic": "Comparator Coverage", "caption": "Synthetic comparator coverage is presented as workflow state.", "decision": "Do not translate unreturned evidence into biological absence."},
        },
        {
            "id": "report_context", "source": "templates/report.md", "document_type": "analysis_report",
            "title": "Context-State Report", "subtitle": "Third report from the same source body",
            "variables": {"topic": "Context Boundaries", "caption": "Synthetic context values do not establish ecology.", "decision": "Keep ecological statements explicitly hypothesis-level."},
        },
        {
            "id": "modeb_alpha", "source": "templates/modeb.md", "document_type": "mode_b_card",
            "title": "Synthetic Mode B Alpha", "authority": "TRUE_DRAFT_NOT_PARENT_AUDITED_NOT_SHELF_PROMOTABLE; synthetic fixture",
            "claim_safety_footer": "TRUE DRAFT; synthetic fixture; capacity is not production and missing evidence is not biological absence.",
            "exact_locus": {"strain": "DEMO-ALPHA", "node_or_contig": "demo_contig_alpha_length_80000", "region": "region001", "bgc_alias": "BGC001"},
            "variables": {"core_gene": "alpha_001", "tailoring_gene": "alpha_002", "transport_gene": "alpha_003"},
        },
        {
            "id": "modeb_beta", "source": "templates/modeb.md", "document_type": "mode_b_card",
            "title": "Synthetic Mode B Beta", "authority": "TRUE_DRAFT_NOT_PARENT_AUDITED_NOT_SHELF_PROMOTABLE; synthetic fixture",
            "claim_safety_footer": "TRUE DRAFT; synthetic fixture; capacity is not production and missing evidence is not biological absence.",
            "exact_locus": {"strain": "DEMO-BETA", "node_or_contig": "demo_contig_beta_length_91000", "region": "region002", "bgc_alias": "BGC002"},
            "variables": {"core_gene": "beta_101", "tailoring_gene": "beta_102", "transport_gene": "beta_103"},
        },
        {
            "id": "modeb_gamma", "source": "templates/modeb.md", "document_type": "mode_b_card",
            "title": "Synthetic Mode B Gamma", "authority": "TRUE_DRAFT_NOT_PARENT_AUDITED_NOT_SHELF_PROMOTABLE; synthetic fixture",
            "claim_safety_footer": "TRUE DRAFT; synthetic fixture; capacity is not production and missing evidence is not biological absence.",
            "exact_locus": {"strain": "DEMO-GAMMA", "node_or_contig": "demo_contig_gamma_length_102000", "region": "region003", "bgc_alias": "BGC003"},
            "variables": {"core_gene": "gamma_201", "tailoring_gene": "gamma_202", "transport_gene": "gamma_203"},
        },
        {
            "id": "report_tree", "source": "templates/tree_report.md", "document_type": "analysis_report",
            "title": "Phylogenetic Tree Presentation", "subtitle": "Caption, methods, source, and interpretation hold",
        },
    ]
    project = {
        "schema_version": "sapote-document-project-1.0",
        "authority": "SYNTHETIC_PILOT_NOT_SCIENTIFIC_VALIDATION_NOT_RELEASE_READY",
        "defaults": {
            "audience": "Sapote-Mamey users and scientific reviewers",
            "authority": "Synthetic document-factory pilot; not a biological result",
            "claim_safety_footer": "Synthetic fixture only; rendering integrity does not validate scientific content.",
            "output_format": "both",
        },
        "documents": documents,
    }
    (ROOT / "sapote-documents.yml").write_text(yaml.safe_dump(project, sort_keys=False, allow_unicode=True), encoding="utf-8")


def main(argv: list[str] | None = None) -> None:
    """v9.7.412: `--out DIR` builds the pilot project under DIR instead of the shipped
    `examples/token_light_documents/pilot_project/` (the test suite passes a temp dir so a full run never
    rewrites release assets; the PNG render is not byte-stable across hosts)."""
    import argparse
    global ROOT, TEMPLATES, ASSETS
    ap = argparse.ArgumentParser(description="Create the deterministic ten-document token-light factory pilot.")
    ap.add_argument("--out", default=None, help="project root to build into (default: the shipped pilot_project/)")
    args = ap.parse_args(argv)
    if args.out:
        ROOT = Path(args.out)
        TEMPLATES = ROOT / "templates"
        ASSETS = TEMPLATES / "assets"
    ROOT.mkdir(parents=True, exist_ok=True)
    make_assets()
    write_templates()
    write_manifest()


if __name__ == "__main__":
    main()
