"""Mamey marker registry draft.

These entries formalize the executable source-derived marker patterns from
mamey/source_scans.py into stable records.  The registry preserves current regex
behavior while adding evidence tiers, HMM/PFAM placeholders, claim ceilings,
wet-lab routing, and source locators for validation.
"""
# ============================================================================
# RELEASE 2 SCOPE — REGISTRY IS DESCRIPTIVE, NOT YET A SCANNING BACKEND
# ----------------------------------------------------------------------------
# These Marker/Cassette objects formalise the detection vocabulary (names,
# Pfam accessions, evidence tiers, claim ceilings) but the Pfam/HMM-profile
# SCANNING they describe does NOT run in the current pipeline. Live detection
# happens in mamey/source_scans.py (regex) and mamey/antismash_evidence.py
# (GBK sec_met_domain Pfam extraction). The Pfam accessions below are targets
# for the Release 2 HMMER/Diamond backend, not active scan rules today.
# Do not treat presence of a Marker here as evidence that its Pfam profile
# was run against the proteome.
# ============================================================================

from __future__ import annotations

from .registry_schema import Marker, Target, validate_stable_ids

MAMEY_MARKERS: tuple[Marker, ...] = (
    # Domain architecture markers from DOMAIN_CLASS_PATTERNS
    Marker("MMK-DOM-001", "NRPS adenylation domain", "mamey_domain_class", "NRPS", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"\bA\b|AMP-binding|adenylation|NRPS_A", required_context="BGC CDS/domain annotation"), Target("pfam", "PF00501", note="AMP-binding/adenylation family; confirm context manually")), ("lcms_msms", "hmm_blast_confirm"), "A-domain-like evidence for NRPS substrate activation.", "Supports NRPS logic, but substrate predictions require A-domain specificity tools or manual review.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.NRPS_A", synonyms=("A-domain", "adenylation")),
    Marker("MMK-DOM-002", "NRPS condensation domain", "mamey_domain_class", "NRPS", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"\bC\b|condensation|NRPS_C", required_context="BGC CDS/domain annotation"), Target("pfam", "PF00668", note="Condensation domain family")), ("lcms_msms", "hmm_blast_confirm"), "Condensation-domain evidence for peptide bond-forming NRPS modules.", "Supports modular NRPS assembly-line interpretation when paired with A/T domains.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.NRPS_C", synonyms=("C-domain",)),
    Marker("MMK-DOM-003", "NRPS thiolation/PCP domain", "mamey_domain_class", "NRPS", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"\bT\b|PCP|thiolation", required_context="BGC CDS/domain annotation"), Target("pfam", "PF00550", note="Phosphopantetheine attachment/carrier domain")), ("lcms_msms", "hmm_blast_confirm"), "Carrier-domain evidence for NRPS modules.", "Supports module completeness when found with A and C domains.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.NRPS_T_PCP", synonyms=("T-domain", "PCP")),
    Marker("MMK-DOM-004", "NRPS epimerization domain", "mamey_domain_class", "NRPS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"\bE\b|epimerization", required_context="BGC CDS/domain annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Tailoring domain that may indicate D-amino-acid incorporation in NRPS products.", "Supports stereochemical complexity but not product identity alone.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.NRPS_E"),
    Marker("MMK-DOM-005", "Thioesterase/release domain", "mamey_domain_class", "release", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"\bTE\b|thioesterase", required_context="BGC CDS/domain annotation"), Target("pfam", "PF00975", note="Thioesterase domain; context dependent")), ("lcms_msms", "hmm_blast_confirm"), "Release-domain evidence for NRPS/PKS termination or macrocyclization.", "Supports product release logic; not diagnostic for compound class alone.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.TE_release", synonyms=("TE", "release domain")),
    Marker("MMK-DOM-006", "PKS ketosynthase", "mamey_domain_class", "PKS", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"PKS_KS|\bKS\b|ketosynthase|ketoacyl synthase", required_context="BGC CDS/domain annotation"), Target("pfam", "PF00109", note="Beta-ketoacyl synthase N-terminal domain")), ("lcms_msms", "hmm_blast_confirm"), "Core carbon-chain elongation marker for PKS logic.", "Supports PKS class assignment when paired with AT/ACP and module context.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.PKS_KS", synonyms=("KS",)),
    Marker("MMK-DOM-007", "PKS acyltransferase", "mamey_domain_class", "PKS", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"PKS_AT|\bAT\b|acyltransferase", required_context="BGC CDS/domain annotation"), Target("pfam", "PF00698", note="Acyl transferase domain")), ("lcms_msms", "hmm_blast_confirm"), "AT-domain evidence for cis-AT PKS modules or acyl-transfer logic.", "Supports PKS module interpretation but does not identify substrate without deeper analysis.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.PKS_AT"),
    Marker("MMK-DOM-008", "PKS dehydratase", "mamey_domain_class", "PKS tailoring", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"PKS_DH|\bDH\b|dehydratase", required_context="BGC CDS/domain annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Reductive-loop marker indicating dehydration during polyketide extension.", "Informs saturation state only in module context.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.PKS_DH"),
    Marker("MMK-DOM-009", "PKS enoylreductase", "mamey_domain_class", "PKS tailoring", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"PKS_ER|\bER\b|enoylreductase", required_context="BGC CDS/domain annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Reductive-loop marker for alkene reduction in PKS modules.", "Informs module reduction pattern but is generic alone.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.PKS_ER"),
    Marker("MMK-DOM-010", "PKS ketoreductase", "mamey_domain_class", "PKS tailoring", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"PKS_KR|\bKR\b|ketoreductase", required_context="BGC CDS/domain annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Reductive-loop marker for beta-keto reduction in PKS modules.", "Informs oxidation state but is generic alone.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.PKS_KR"),
    Marker("MMK-DOM-011", "PKS acyl carrier protein", "mamey_domain_class", "PKS", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"PKS_ACP|\bACP\b|acyl carrier", required_context="BGC CDS/domain annotation"), Target("pfam", "PF00550", note="Carrier-domain family overlaps with PCP; require context")), ("lcms_msms", "hmm_blast_confirm"), "Carrier-domain evidence for PKS modules.", "Supports PKS architecture only with KS/AT/module context.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.PKS_ACP"),
    Marker("MMK-DOM-012", "RiPP precursor clue", "mamey_domain_class", "RiPP", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"precursor|leader peptide|core peptide", required_context="BGC CDS/product annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Annotation clue for RiPP precursor peptides.", "Useful when paired with maturation enzymes; weak by itself because annotation can be generic.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.RiPP_precursor"),
    Marker("MMK-DOM-013", "YcaO/TOMM cyclodehydratase", "mamey_domain_class", "RiPP maturation", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"YcaO|cyclodehydratase", required_context="RiPP/TOMM/thioamide context"), Target("pfam", "PF02624", note="YcaO family")), ("lcms_msms", "hmm_blast_confirm"), "YcaO-family marker for azoline-forming TOMMs or thioamide-related RiPP maturation.", "Raises priority for azole-containing RiPP or thioamidated peptide hypotheses when context is concordant.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.YcaO_TOMM; UMED_PATTERNS.YcaO_TfuA_thioamide", synonyms=("YcaO", "TOMM")),
    Marker("MMK-DOM-014", "Halogenase", "mamey_domain_class", "halogenation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"(?<!de)halogenase", required_context="BGC or flank annotation"),), ("lcms_msms", "hmm_blast_confirm"), "General halogenase annotation signal.", "Supports halogenated natural-product potential; exact halogenase subclass requires manual/HMM confirmation.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.Halogenase"),
    Marker("MMK-DOM-015", "Glycosyltransferase", "mamey_domain_class", "glycosylation", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"glycosyltransferase|\bGT\b", required_context="BGC/flank annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Tailoring marker for glycosylated natural products.", "Supports sugar tailoring but does not assign sugar identity alone.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.Glycosyltransferase"),
    Marker("MMK-DOM-016", "Methyltransferase", "mamey_domain_class", "tailoring", "TIER_4_GENERIC", "LOW", (Target("regex", r"methyltransferase", required_context="BGC/flank annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Generic methylation tailoring marker.", "Useful as context only; common across many pathways.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.Methyltransferase"),
    Marker("MMK-DOM-017", "Oxidoreductase/oxygenase", "mamey_domain_class", "tailoring", "TIER_4_GENERIC", "LOW", (Target("regex", r"oxidoreductase|dehydrogenase|oxygenase", required_context="BGC/flank annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Broad redox tailoring clue.", "Never class-definitive without a more specific family call.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.Oxidoreductase"),
    Marker("MMK-DOM-018", "Aminotransferase", "mamey_domain_class", "tailoring", "TIER_4_GENERIC", "LOW", (Target("regex", r"aminotransferase|transaminase", required_context="BGC/flank annotation"),), ("lcms_msms", "hmm_blast_confirm"), "Generic aminotransferase tailoring clue.", "Context-only evidence for amination or sugar/aminocyclitol logic.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.Aminotransferase"),
    Marker("MMK-DOM-019", "Transporter", "mamey_domain_class", "transport", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"transporter|efflux|exporter", required_context="BGC/flank annotation"),), ("inventory_only",), "Generic transporter clue for export or self-protection context.", "Does not prove bioactivity or resistance; use only as support.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.Transporter"),
    Marker("MMK-DOM-020", "Regulator", "mamey_domain_class", "regulation", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"regulator|transcriptional", required_context="BGC/flank annotation"),), ("inventory_only",), "Generic regulator clue for pathway control.", "Does not assign expression state without TFBS/culture evidence.", source_locator="mamey/source_scans.py:DOMAIN_CLASS_PATTERNS.Regulator"),

    # Chitin/glycan ecology markers
    Marker("MMK-CGAD-001", "GH18 chitinase", "mamey_chitin_glycan", "chitin/glycan ecology", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"gh18|glycoside hydrolase family 18|chitinase"), Target("pfam", "PF00704", note="GH18 catalytic domain")), ("ecology_assay", "hmm_blast_confirm"), "Chitinase marker for chitin utilization/antifungal ecology hypotheses.", "Supports chitin-linked ecological interpretation when full-proteome scope is available.", source_locator="mamey/source_scans.py:CHITINASE_PATTERNS.GH18"),
    Marker("MMK-CGAD-002", "GH19 chitinase", "mamey_chitin_glycan", "chitin/glycan ecology", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"gh19|glycoside hydrolase family 19"), Target("pfam", "PF00182", note="GH19 catalytic domain")), ("ecology_assay", "hmm_blast_confirm"), "GH19 chitinase marker for chitin utilization/defense capacity.", "Supports antifungal ecology hypotheses when confirmed genome-wide.", source_locator="mamey/source_scans.py:CHITINASE_PATTERNS.GH19"),
    Marker("MMK-CGAD-003", "AA10/LPMO", "mamey_chitin_glycan", "chitin/glycan ecology", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"aa10|lpmo|lytic polysaccharide monooxygenase"), Target("pfam", "PF03067", note="AA10/LPMO family, context dependent")), ("ecology_assay", "hmm_blast_confirm"), "Oxidative polysaccharide-degradation marker.", "Supports chitin/glycan remodeling ecology but requires protein-family confirmation.", source_locator="mamey/source_scans.py:CHITINASE_PATTERNS.AA10_LPMO"),
    Marker("MMK-CGAD-004", "Chitin-binding CBM", "mamey_chitin_glycan", "chitin/glycan ecology", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"chitin.?binding|cbm|carbohydrate.binding"),), ("ecology_assay", "hmm_blast_confirm"), "Carbohydrate-binding module clue for chitin/glycan interaction.", "Supportive only; CBM text alone is broad.", source_locator="mamey/source_scans.py:CHITINASE_PATTERNS.CBM_CHITIN"),
    Marker("MMK-CGAD-005", "GlcNAc/Nag/DasR clue", "mamey_chitin_glycan", "chitin/glycan ecology", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"glcnac|n-acetylglucosamine|nag[a-z]|dasr"),), ("ecology_assay", "tfbs_induction"), "Marker group for GlcNAc catabolism and DasR-linked chitin response.", "Supports CGAD-style induction hypotheses but requires gene identity and network context.", source_locator="mamey/source_scans.py:CHITINASE_PATTERNS.GlcNAc"),

    # Regulator, transporter, resistance, CCTT, FLBR, UMED and TFBS markers are intentionally compact below.
    Marker("MMK-REG-001", "DasR/GntR regulator", "mamey_regulator", "regulation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"dasr|gntr"),), ("tfbs_induction", "ecology_assay"), "DasR/GntR-family regulatory clue for GlcNAc/chitin or carbon-response hypotheses.", "Supports TFBS-guided induction planning, not expression proof.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.DasR_GntR"),
    Marker("MMK-REG-002", "LuxR regulator", "mamey_regulator", "regulation", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"luxr"),), ("tfbs_induction",), "LuxR-family regulatory clue.", "Context-only without pathway-specific evidence.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.LuxR"),
    Marker("MMK-REG-003", "TetR regulator", "mamey_regulator", "regulation", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"tetr"),), ("tfbs_induction",), "TetR-family regulatory clue, including possible antibiotic-feedback repressors.", "Context-only without target motif or pathway linkage.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.TetR"),
    Marker("MMK-REG-004", "LysR regulator", "mamey_regulator", "regulation", "TIER_4_GENERIC", "INVENTORY_ONLY", (Target("regex", r"lysr"),), ("inventory_only",), "Generic LysR-family regulator clue.", "Inventory only unless a pathway-specific link is shown.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.LysR"),
    Marker("MMK-REG-005", "SARP regulator", "mamey_regulator", "regulation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"sarp|streptomyces antibiotic regulatory protein"),), ("tfbs_induction",), "Pathway-regulatory clue common in actinomycete antibiotic BGCs.", "Supports activation strategy but not product identity.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.SARP"),
    Marker("MMK-REG-006", "MarR regulator", "mamey_regulator", "regulation", "TIER_4_GENERIC", "INVENTORY_ONLY", (Target("regex", r"marr"),), ("inventory_only",), "Generic MarR-family regulator clue.", "Inventory only unless linked to a validated pathway.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.MarR"),
    Marker("MMK-REG-007", "LacI regulator", "mamey_regulator", "regulation", "TIER_4_GENERIC", "INVENTORY_ONLY", (Target("regex", r"laci"),), ("inventory_only",), "Generic LacI-family regulator clue.", "Inventory only unless linked to pathway activation.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.LacI"),
    Marker("MMK-REG-008", "AraC regulator", "mamey_regulator", "regulation", "TIER_4_GENERIC", "INVENTORY_ONLY", (Target("regex", r"arac"),), ("inventory_only",), "Generic AraC-family regulator clue.", "Inventory only unless linked to pathway activation.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.AraC"),
    Marker("MMK-REG-009", "Two-component regulator", "mamey_regulator", "regulation", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"response regulator|histidine kinase|two-component"),), ("tfbs_induction",), "Two-component system clue near BGCs or ecological pathways.", "Context-only without ligand/target evidence.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.TwoComponent"),
    Marker("MMK-REG-010", "Fur/Zur regulator", "mamey_regulator", "iron/zinc regulation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"\bfur\b|\bzur\b|ferric uptake regulator|zinc uptake regulator"),), ("tfbs_induction", "ecology_assay"), "Iron/zinc-responsive regulator clue for siderophore/metallophore ecology.", "Supports iron-limitation induction hypotheses.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.Fur_Zur"),
    Marker("MMK-REG-011", "IolR regulator", "mamey_regulator", "polyol regulation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"iolr"),), ("tfbs_induction", "ecology_assay"), "Inositol/polyol-response regulator clue.", "Supports polyol-induction hypotheses where habitat context fits.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.IolR"),
    Marker("MMK-REG-012", "PhoP/PhoR regulator", "mamey_regulator", "phosphate regulation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"phop|phor"),), ("tfbs_induction",), "Phosphate-response regulatory clue.", "Supports phosphate-limitation induction hypotheses.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.PhoP"),
    Marker("MMK-REG-013", "OsdR regulator", "mamey_regulator", "osmotic/stress regulation", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"osdr"),), ("tfbs_induction",), "OsdR-family regulatory clue.", "Context-only unless linked to a BGC and induction model.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.OsdR"),
    Marker("MMK-REG-014", "GBL/AdpA regulatory clue", "mamey_regulator", "GBL regulation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"gamma-butyrolactone|\bbutyrolactone\b|a-factor receptor|autoregulator receptor|\barpr\b|\barpa\b|\bscbr\b|\bbara\b|\badpa\b|\bbldh\b"),), ("tfbs_induction",), "Gamma-butyrolactone/quorum-response regulatory clue (F11-widened: arpa/bara/bldh/scbr/adpa + a-factor/autoregulator receptors).", "Supports activation models but not product identity.", source_locator="mamey/source_scans.py:REGULATOR_PATTERNS.GBL"),

    Marker("MMK-TRN-001", "ABC transporter", "mamey_transporter", "transport", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"abc transporter|atp-binding cassette"),), ("inventory_only",), "ABC transporter clue.", "Use only as export/immunity support.", source_locator="mamey/source_scans.py:TRANSPORTER_PATTERNS.ABC"),
    Marker("MMK-TRN-002", "MFS transporter", "mamey_transporter", "transport", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"major facilitator|\bmfs\b"),), ("inventory_only",), "MFS transporter clue.", "Use only as context.", source_locator="mamey/source_scans.py:TRANSPORTER_PATTERNS.MFS"),
    Marker("MMK-TRN-003", "RND transporter", "mamey_transporter", "transport", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"rnd transporter|resistance-nodulation"),), ("inventory_only",), "RND transporter clue.", "Use only as context.", source_locator="mamey/source_scans.py:TRANSPORTER_PATTERNS.RND"),
    Marker("MMK-TRN-004", "MATE transporter", "mamey_transporter", "transport", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"mate transporter"),), ("inventory_only",), "MATE transporter clue.", "Use only as context.", source_locator="mamey/source_scans.py:TRANSPORTER_PATTERNS.MATE"),
    Marker("MMK-TRN-005", "Efflux clue", "mamey_transporter", "transport", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"efflux"),), ("inventory_only",), "Generic efflux clue.", "Do not treat as self-resistance by itself.", source_locator="mamey/source_scans.py:TRANSPORTER_PATTERNS.Efflux"),
    Marker("MMK-TRN-006", "Export/secretion clue", "mamey_transporter", "transport", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"exporter|secretion"),), ("inventory_only",), "Generic export/secretion clue.", "Do not treat as production proof.", source_locator="mamey/source_scans.py:TRANSPORTER_PATTERNS.Export"),

    Marker("MMK-RES-001", "Beta-lactamase-fold protein", "mamey_resistance", "resistance", "TIER_4_GENERIC", "LOW", (Target("regex", r"beta.?lactamase|metallo-beta-lactamase"),), ("hmm_blast_confirm",), "Broad beta-lactamase-fold/resistance clue.", "Often generic; requires class concordance before self-protection use.", source_locator="mamey/source_scans.py:RESISTANCE_PATTERNS.Beta_lactamase_fold"),
    Marker("MMK-RES-002", "Erm rRNA methylase", "mamey_resistance", "self-protection", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"\berm\b|rrna methyltransferase|23s rrna methyltransferase|erythromycin resistance methyltransferase"),), ("hmm_blast_confirm",), "MLS resistance marker potentially concordant with macrolide/lincosamide pathways.", "Requires HGT guard and class concordance.", source_locator="mamey/source_scans.py:RESISTANCE_PATTERNS.Erm_methylase"),
    Marker("MMK-RES-003", "VanHAX-like resistance", "mamey_resistance", "self-protection", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"\bvanh\b|\bvana\b|\bvanx\b|d-ala-d-lac|vancomycin resistance"),), ("hmm_blast_confirm",), "Glycopeptide-resistance/self-protection clue.", "Requires proximity, HGT guard, and glycopeptide-class concordance.", source_locator="mamey/source_scans.py:RESISTANCE_PATTERNS.VanHAX_like"),
    Marker("MMK-RES-004", "APH/AAC aminoglycoside resistance", "mamey_resistance", "self-protection", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"aminoglycoside phosphotransferase|aminoglycoside acetyltransferase|\baph\b|\baac\b"),), ("hmm_blast_confirm",), "Aminoglycoside resistance/self-protection clue.", "Requires aminoglycoside/aminocyclitol biosynthetic concordance.", source_locator="mamey/source_scans.py:RESISTANCE_PATTERNS.APH_AAC"),
    Marker("MMK-RES-005", "Fosfomycin self-protection", "mamey_resistance", "self-protection", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"\bfoma\b|\bfomb\b|fosfomycin resistance"),), ("hmm_blast_confirm",), "FomA/FomB-like fosfomycin resistance clue.", "Strong only when paired with phosphonate/PepM biosynthesis and proximity.", source_locator="mamey/source_scans.py:RESISTANCE_PATTERNS.Fosfomycin"),
    Marker("MMK-RES-006", "General self-resistance/immunity", "mamey_resistance", "self-protection", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"resistance protein|immunity protein|self-resistance"),), ("inventory_only",), "Generic resistance/immunity wording.", "Do not use for self-protection claims without class-specific evidence.", source_locator="mamey/source_scans.py:RESISTANCE_PATTERNS.Self_resistance_general"),

    # CCTT triggers
    Marker("MMK-CCTT-001", "T43-HAL halogenase trigger", "mamey_cctt", "cryptic/tailoring trigger", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"(?<!de)halogenase|flavin-dependent halogenase|tryptophan halogenase"),), ("lcms_msms", "hmm_blast_confirm"), "Halogenation trigger for cryptic-class review.", "Supports halogenated-product search; needs subclass confirmation.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-HAL_halogenase"),
    Marker("MMK-CCTT-002", "T43-XHAL fluorinase/chlorinase trigger", "mamey_cctt", "organohalogen trigger", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"fluorinase|chlorinase|\bsall\b|\bfla\b|sam-dependent halogenase"),), ("lcms_msms", "hmm_blast_confirm"), "SAM-dependent organohalogen building-block trigger.", "High-value lead when context supports SalL/FlA-like chemistry.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-XHAL_fluorinase_chlorinase"),
    Marker("MMK-CCTT-003", "T43-PHO phosphonate trigger", "mamey_cctt", "phosphonate", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"phosphonate|pep mutase|phosphoenolpyruvate mutase"),), ("lcms_msms", "hmm_blast_confirm"), "Phosphonate biosynthesis trigger.", "Strong when PepM-like evidence is confirmed.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-PHO_phosphonate"),
    Marker("MMK-CCTT-004", "T43-NUC nucleoside trigger", "mamey_cctt", "nucleoside", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"nucleoside|nikkomycin|nikj|nikd|polyoxin"),), ("lcms_msms", "hmm_blast_confirm", "antifungal_fractionation"), "Peptidyl-nucleoside/nucleoside-like trigger.", "Strong antifungal-track cue when Nik/Pol-like markers are confirmed.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-NUC_nucleoside"),
    Marker("MMK-CCTT-005", "T43-AMC aminocyclitol trigger", "mamey_cctt", "aminocyclitol", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"aminocyclitol|dois|btrc|2-deoxy-scyllo-inosose"),), ("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), "Aminocyclitol/aminoglycoside-class trigger.", "Strong when DOIS/BtrC-like evidence is confirmed.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-AMC_aminocyclitol"),
    Marker("MMK-CCTT-006", "T43-ENE enediyne trigger", "mamey_cctt", "enediyne", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"enediyne"),), ("lcms_msms", "hmm_blast_confirm", "safety_cytotoxicity"), "Enediyne-class trigger.", "Requires safety/cytotoxicity caution and hallmark-gene review.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-ENE_enediyne"),
    Marker("MMK-CCTT-007", "T43-LAN lanthipeptide trigger", "mamey_cctt", "RiPP", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"lanthipeptide|lantibiotic|lanc|lanm"),), ("lcms_msms", "hmm_blast_confirm"), "Lanthipeptide/RiPP trigger.", "Requires precursor and maturation review before production claims.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-LAN_lanthipeptide"),
    Marker("MMK-CCTT-008", "T43-LASSO lasso peptide trigger", "mamey_cctt", "RiPP", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"lassopeptide|lasso peptide"),), ("lcms_msms", "hmm_blast_confirm"), "Lasso-peptide trigger.", "High-confidence only with lasso cyclase/protease/RRE constellation.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-LASSO_lassopeptide"),
    Marker("MMK-CCTT-009", "T43-THA thioamide trigger", "mamey_cctt", "thioamide", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"thioamide|ycaO"),), ("lcms_msms", "hmm_blast_confirm"), "Thioamide/thioamidated RiPP trigger.", "High-value rare-peptide lead when YcaO/TfuA context is present.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-THA_thioamide"),
    Marker("MMK-CCTT-010", "T43-DKP CDPS trigger", "mamey_cctt", "DKP/CDPS", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"cyclodipeptide synthase|cdps|diketopiperazine"),), ("lcms_msms", "hmm_blast_confirm"), "Cyclodipeptide synthase/DKP trigger.", "Class depends on CDPS plus oxidase/context grade.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-DKP_cdps"),
    Marker("MMK-CCTT-011", "T43-IDC indolocarbazole trigger", "mamey_cctt", "indolocarbazole", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"indolocarbazole|rebeccamycin|staurosporine|indsynth"),), ("lcms_msms", "hmm_blast_confirm", "safety_cytotoxicity"), "Indolocarbazole-class trigger.", "Requires cytotoxicity caution and multi-gene confirmation.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-IDC_indolocarbazole"),
    Marker("MMK-CCTT-012", "T43-PTM HSAF/tetramate trigger", "mamey_cctt", "PKS-NRPS/tetramate", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"hsaf|maltophilin|tetramate|pks-nrps"),), ("lcms_msms", "hmm_blast_confirm", "antifungal_fractionation"), "Polyene tetramate/HSAF-like trigger.", "Strong antifungal-track cue when PKS-NRPS architecture is confirmed.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-PTM_hsaf_tetramate"),
    Marker("MMK-CCTT-013", "T43-TET tetronate/spirotetronate trigger", "mamey_cctt", "tetronate", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"tetronate|spirotetronate|fkbh|glyceryl"),), ("lcms_msms", "hmm_blast_confirm"), "Tetronate/spirotetronate trigger.", "Strong only with FkbH/ACP and pathway context.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-TET_tetronate_spirotetronate"),
    Marker("MMK-CCTT-014", "T43-NN N-N/diazo trigger", "mamey_cctt", "N-N bond/diazo", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"n-n bond|diazo|creE|creD|azoxy|hydrazine"),), ("lcms_msms", "hmm_blast_confirm", "safety_cytotoxicity"), "N-N bond/diazo/azoxy biosynthesis trigger.", "High novelty/safety cue with CreE/CreD-like evidence.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-NN_n_n_bond"),
    # v9.7.119->1.9.99 class-defining triggers (registry_inventory_v1.9.4.json MMK-CCTT-015..018 already
    # carried these; the hardcoded MAMEY_MARKERS tuple below never picked them up until this fix — the
    # same registry-drift bug class as good_guesses.py/diagnostic_rescue.py this session).
    Marker("MMK-CCTT-015", "T43-BLA beta-lactam trigger", "mamey_cctt", "betalactam", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"\bnocardicin\b|isopenicillin n synthase(?!\s*family)|\bpcbab\b|\bpcbc\b|acv synthetase|beta-lactam synthetase|\bbls\b|clavaminate synthase|deacetoxycephalosporin|monobactam|\bnat\b nocardicin"),), ("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), "Beta-lactam biosynthesis trigger (nocardicin/monobactam, isopenicillin/ACV, clavam).", "Strong when ACV/IPNS or nocardicin/clavam markers are confirmed.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-BLA_betalactam"),
    Marker("MMK-CCTT-016", "T43-PYE polyene macrolide trigger", "mamey_cctt", "polyene_macrolide", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"(?<!aryl)polyene macrolide|(?<!aryl)polyene antifungal|\bnatamycin\b|\bpimaricin\b|\bcandicidin\b|\bamphotericin\b|\bnystatin\b|\bfilipin\b|\brimocidin\b|\bfaeriefungin\b|\btetramycin\b|\blucensomycin\b|\bpartricin\b|\bperimycin\b|\baureofungin\b|\bhamycin\b|\btrichomycin\b|\blevorin\b|\bfungichromin\b|\bselvamicin\b|\breedsmycin\b|\btetraene\b|\bpentaene\b|\bhexaene\b|\bheptaene\b"),), ("lcms_msms", "hmm_blast_confirm", "antifungal_fractionation"), "Polyene-macrolide antifungal trigger; arylpolyene pigment excluded via negative lookbehind.", "Strong when a modular PKS backbone (>=4 PKS_KS) is present.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-PYE_polyene_macrolide"),
    Marker("MMK-CCTT-017", "T43-GPA glycopeptide trigger", "mamey_cctt", "glycopeptide", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"\boxyB\b|\boxyA\b|\boxyC\b|\bdpgs\b|3,5-dihydroxyphenylglycine|4-hydroxyphenylglycine|\bhpg\b aminotransferase|\bglycopeptide\b|\bvancomycin\b|\bteicoplanin\b|\bbalhimycin\b|\bchloroeremomycin\b|\bpekiskomycin\b|\bristocetin\b|\bristomycin\b"),), ("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), "Glycopeptide antibacterial trigger; OxyB/OxyA/OxyC and DPGS/HPG machinery are glycopeptide-specific committed markers.", "Strong when corroborated by NRPS + halogenase + glycosyltransferase.", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-GPA_glycopeptide"),
    Marker("MMK-CCTT-018", "T43-BLT betalactone trigger", "mamey_cctt", "betalactone", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"\bbetalactone\b|\bbeta-lactone\b|\bsalinosporamide\b|\bplatensimycin\b|\bplatencin\b|\blactacystin\b|\bebelactone\b|\bovalicin\b"),), ("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), "Betalactone trigger; committed logic is PEP-utilizer + biotin-carboxylase pair, named compounds fire directly.", "Strong when PEP-utilizer + biotin-carboxylase co-occur (platensimycin class).", source_locator="mamey/source_scans.py:CCTT_PATTERNS.T43-BLT_betalactone"),

    Marker("MMK-FLBR-001", "Modular PKS KS fragment", "mamey_flbr", "fragment rescue", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"modular.?ks|ketosynthase|pks ks|beta-ketoacyl synthase"),), ("long_read_rescue", "hmm_blast_confirm"), "Fragment clue for large modular PKS rescue.", "Raises sequencing/rescue priority rather than claim confidence.", source_locator="mamey/source_scans.py:FLBR_PATTERNS.mod_KS"),
    Marker("MMK-FLBR-002", "Hybrid PKS/NRPS KS fragment", "mamey_flbr", "fragment rescue", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"hybrid.?ks|nrps.*pks|pks.*nrps"),), ("long_read_rescue", "hmm_blast_confirm"), "Fragment clue for PKS-NRPS hybrid rescue.", "Raises rescue priority.", source_locator="mamey/source_scans.py:FLBR_PATTERNS.hyb_KS"),
    Marker("MMK-FLBR-003", "Trans-AT PKS fragment", "mamey_flbr", "fragment rescue", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"trans.?at|trans-acyltransferase"),), ("long_read_rescue", "hmm_blast_confirm"), "Trans-AT PKS fragment clue.", "Requires trans-AT architecture review.", source_locator="mamey/source_scans.py:FLBR_PATTERNS.tra_KS"),
    Marker("MMK-FLBR-004", "Mega-NRPS fragment", "mamey_flbr", "fragment rescue", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"nonribosomal peptide synthetase"),), ("long_read_rescue", "hmm_blast_confirm"), "Fragment clue for large NRPS rescue.", "Raises rescue priority especially at contig edges.", source_locator="mamey/source_scans.py:FLBR_PATTERNS.mega_NRPS"),

    Marker("MMK-UMED-001", "LanP/S8 protease", "mamey_umed", "RiPP maturation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"(?<![A-Za-z])lanp(?![A-Za-z])|subtilisin|peptidase[ _-]?s8|serine protease"),), ("lcms_msms", "hmm_blast_confirm"), "Lanthipeptide maturation protease clue.", "Supports maturation capacity when proximal to lanthipeptide BGC.", source_locator="mamey/source_scans.py:UMED_PATTERNS.LanP_S8_protease"),
    Marker("MMK-UMED-002", "LanT/C39 transporter-peptidase", "mamey_umed", "RiPP maturation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"(?<![A-Za-z])lant(?![A-Za-z_])|(?<![A-Za-z])c39(?![A-Za-z])|peptidase.*abc|abc.*peptidase"),), ("lcms_msms", "hmm_blast_confirm"), "Lanthipeptide processing/export clue.", "Supports maturation/export but requires proximity and domain confirmation.", source_locator="mamey/source_scans.py:UMED_PATTERNS.LanT_C39_transporter_peptidase"),
    Marker("MMK-UMED-003", "FlaP/AplP/S9 protease", "mamey_umed", "RiPP maturation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"(?<![A-Za-z])flap(?![A-Za-z])(?!\s*endonuclease)|(?<![A-Za-z])aplp(?![A-Za-z])|peptidase[ _-]?s9"),), ("lcms_msms", "hmm_blast_confirm"), "RiPP maturation protease clue.", "Supports maturation only in pathway context.", source_locator="mamey/source_scans.py:UMED_PATTERNS.FlaP_AplP_S9_protease"),
    Marker("MMK-UMED-004", "M16B metalloprotease", "mamey_umed", "RiPP maturation", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"m16|metalloprotease|pitrilysin"),), ("lcms_msms", "hmm_blast_confirm"), "M16B-style lanthipeptide maturation clue.", "High-value only with paired subunit/context confirmation.", source_locator="mamey/source_scans.py:UMED_PATTERNS.M16B_metalloprotease"),
    Marker("MMK-UMED-005", "YcaO/TfuA thioamide maturation", "mamey_umed", "RiPP maturation", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"ycao|tfua|thioamide"),), ("lcms_msms", "hmm_blast_confirm"), "Thioamide maturation clue.", "Strong rare-peptide cue when YcaO/TfuA are concordant.", source_locator="mamey/source_scans.py:UMED_PATTERNS.YcaO_TfuA_thioamide"),
    Marker("MMK-UMED-006", "RiPP recognition element", "mamey_umed", "RiPP maturation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"ripp recognition element|(?<![A-Za-z])rre(?![A-Za-z])"),), ("lcms_msms", "hmm_blast_confirm"), "RRE clue for RiPP maturation enzyme specificity.", "Supports RiPP logic but is not sufficient alone.", source_locator="mamey/source_scans.py:UMED_PATTERNS.RiPP_RRE"),
    Marker("MMK-UMED-007", "Nucleoside maturation clue", "mamey_umed", "nucleoside", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"nik|nucleoside|radical sam|aminotransferase"),), ("lcms_msms", "hmm_blast_confirm"), "Broad nucleoside-tailoring clue.", "Needs pathway-specific marker confirmation.", source_locator="mamey/source_scans.py:UMED_PATTERNS.nucleoside_maturation"),

    # TFBS motifs as preliminary motif markers
    Marker("MMK-TFBS-001", "DasR-like palindrome motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "TGTCTAGACNA"), Target("motif", "TGTNANNNNNNTNACA")), ("tfbs_induction",), "Preliminary DasR-like upstream motif.", "Motif-only; require calibrated background scoring before claims.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.DasR_like_palindrome"),
    Marker("MMK-TFBS-002", "DmdR iron-box-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "TTAGGTTAGGCTAACCTAA"),), ("tfbs_induction", "ecology_assay"), "Preliminary DmdR/Fur iron-box-like motif.", "Motif-only; interpret as induction planning evidence.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.DmdR_iron_box_like"),
    Marker("MMK-TFBS-003", "LexA/SOS-like motif", "mamey_tfbs", "TFBS", "TIER_4_GENERIC", "INVENTORY_ONLY", (Target("motif", "CTGTATATATATACAG"), Target("motif", "CGAACNNNNGTTCG")), ("inventory_only",), "Preliminary LexA/SOS-like motif.", "Motif-only; inventory/planning evidence.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.LexA_SOS_like"),
    Marker("MMK-TFBS-004", "BldD-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "GTCTAGAC"),), ("tfbs_induction",), "Preliminary BldD-like motif.", "Motif-only; requires calibration.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.BldD_like"),
    Marker("MMK-TFBS-005", "FuR-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "GATAATGATAATCATTATC"),), ("tfbs_induction", "ecology_assay"), "Preliminary FuR-like motif.", "Motif-only; supports iron-induction planning.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.FuR_like"),
    Marker("MMK-TFBS-006", "Zur-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "AAATGTTATAACATTT"),), ("tfbs_induction", "ecology_assay"), "Preliminary Zur-like motif.", "Motif-only; supports zinc/metal induction planning.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.Zur_like"),
    Marker("MMK-TFBS-007", "IolR-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "TGTGANNNNNNTCACA"),), ("tfbs_induction",), "Preliminary IolR-like motif.", "Motif-only; supports polyol induction planning.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.IolR_like"),
    Marker("MMK-TFBS-008", "PhoP-box-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "GTTCANNNNNGTTC"),), ("tfbs_induction",), "Preliminary PhoP/PhoR-like motif.", "Motif-only; supports phosphate-induction planning.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.PhoP_box_like"),
    Marker("MMK-TFBS-009", "ANR/FNR-like motif", "mamey_tfbs", "TFBS", "TIER_4_GENERIC", "INVENTORY_ONLY", (Target("motif", "TTGATNNNNATCAA"),), ("inventory_only",), "Preliminary oxygen/redox regulator motif.", "Inventory only unless calibrated.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.ANR_FNR_like"),
    Marker("MMK-TFBS-010", "GBL/AdpA-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "TGGCSNGWWY"),), ("tfbs_induction",), "Preliminary AdpA/GBL-like motif.", "Motif-only; supports GBL-style activation planning.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.GBL_AdpA_like"),
    Marker("MMK-TFBS-011", "SARP/BTAD-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "TCGAGNNNNCTCGA"),), ("tfbs_induction",), "Preliminary SARP/BTAD-like motif.", "Motif-only; supports pathway-regulator hypotheses.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.SARP_BTAD_like"),
    Marker("MMK-TFBS-012", "PAS-LuxR-like motif", "mamey_tfbs", "TFBS", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("motif", "ACCTGTNNNNACAGGT"),), ("tfbs_induction",), "Preliminary PAS-LuxR-like motif.", "Motif-only; supports regulator hypotheses.", source_locator="mamey/source_scans.py:TFBS_MOTIFS.PAS_LuxR_like"),
)

validate_stable_ids(MAMEY_MARKERS, "MMK-")

MAMEY_MARKER_BY_ID = {m.id: m for m in MAMEY_MARKERS}
MAMEY_MARKER_BY_NAME = {m.name: m for m in MAMEY_MARKERS}
