"""Mamey cassette registry draft.

This file formalizes CASSETTE_PATTERNS from mamey/source_scans.py into stable
cassette records.  Required/optional marker fields reference stable marker IDs
from mamey_markers.py where practical; regex targets preserve current v1.9.3
behavior for backward compatibility.
"""
# ============================================================================
# RELEASE 2 SCOPE — PFAM SCANNING BACKEND IS DEFERRED; REGISTRY IS ACTIVE
# ----------------------------------------------------------------------------
# These Marker/Cassette objects formalise the detection vocabulary (names,
# Pfam accessions, evidence tiers, claim ceilings) and ARE used at runtime
# for the cassette crosswalk and naming layer. However, the Pfam/HMM-profile
# SCANNING they describe does NOT run in the current pipeline. Live detection
# happens in mamey/source_scans.py (regex) and mamey/antismash_evidence.py
# (GBK sec_met_domain Pfam extraction). The Pfam accessions below are targets
# for the Release 2 HMMER/Diamond backend, not active scan rules today.
# Do not treat presence of a Marker here as evidence that its Pfam profile
# was run against the proteome.
# ============================================================================

from __future__ import annotations

from .registry_schema import Cassette, Target, validate_stable_ids

MAMEY_CASSETTES: tuple[Cassette, ...] = (
    Cassette("MMC-001", "Release and macrocyclization cassette", "mamey_cassette", "release_macrocyclization", "TIER_3_CONTEXT_TAILORING", "LOW", required_markers=("MMK-DOM-005",), targets=(Target("regex", r"thioesterase|\bte\b|cyclase|macrocycl|esterase|reductase release"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Release, cyclization, esterase, or reductive-release signals used to interpret BGC product termination.", positive_interpretation="Supports release logic and possible macrocyclization when paired with NRPS/PKS architecture.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.release_macrocyclization"),
    Cassette("MMC-002", "Glycosylation cassette", "mamey_cassette", "glycosylation", "TIER_3_CONTEXT_TAILORING", "LOW", required_markers=("MMK-DOM-015",), targets=(Target("regex", r"glycosyltransferase|glycosyl|sugar|deoxysugar|gt\b"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Sugar-tailoring signal set for glycosylated natural-product hypotheses.", positive_interpretation="Supports sugar/deoxysugar tailoring but not sugar identity without deeper annotation.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.glycosylation"),
    Cassette("MMC-003", "Halogenation cassette", "mamey_cassette", "halogenation", "TIER_2_CLASS_SUPPORTING", "MODERATE", optional_markers=("MMK-DOM-014", "MMK-CCTT-001", "MMK-CCTT-002"), targets=(Target("regex", r"(?<!de)halogenase|fluorinase|chlorinase|brominase"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Halogenase and organohalogen-building-block evidence for halogenated natural-product potential.", positive_interpretation="Elevates halogenated metabolite search priority; exact subclass requires confirmation.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.halogenation"),
    Cassette("MMC-004", "Phosphonate cassette", "mamey_cassette", "phosphonate", "TIER_1_DIAGNOSTIC", "HIGH", optional_markers=("MMK-CCTT-003", "MMK-RES-005"), targets=(Target("regex", r"phosphonate|pep mutase|phosphoenolpyruvate mutase|foma|fomb"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), description="Phosphonate biosynthesis/self-protection signal set.", positive_interpretation="High-value antibacterial/antimetabolite hypothesis when PepM-like biosynthesis and FomA/FomB-like resistance are concordant.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.phosphonate"),
    Cassette("MMC-005", "Nucleoside cassette", "mamey_cassette", "nucleoside", "TIER_1_DIAGNOSTIC", "HIGH", optional_markers=("MMK-CCTT-004", "MMK-UMED-007"), targets=(Target("regex", r"nucleoside|nikkomycin|polyoxin|nikj|nikd"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "antifungal_fractionation"), description="Peptidyl-nucleoside or nucleoside-like biosynthesis signal set.", positive_interpretation="Strong Candida/antifungal-track cue when Nik/Pol-like markers are confirmed.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.nucleoside"),
    Cassette("MMC-006", "Aminoglycoside/aminocyclitol cassette", "mamey_cassette", "aminoglycoside_aminocyclitol", "TIER_1_DIAGNOSTIC", "HIGH", optional_markers=("MMK-CCTT-005", "MMK-RES-004"), targets=(Target("regex", r"aminoglycoside|aminocyclitol|dois|btrc"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), description="Aminocyclitol/aminoglycoside biosynthesis and self-protection signal set.", positive_interpretation="Strong antibacterial-track cue when DOIS/BtrC-like evidence is confirmed.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.aminoglycoside_aminocyclitol"),
    Cassette("MMC-007", "Tetronate/spirotetronate cassette", "mamey_cassette", "tetronate_spirotetronate", "TIER_1_DIAGNOSTIC", "HIGH", optional_markers=("MMK-CCTT-013",), targets=(Target("regex", r"tetronate|spirotetronate|fkbh|glyceryl"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Tetronate/spirotetronate building-block signal set.", positive_interpretation="High-value polyketide-tailoring cue when FkbH/ACP context is present.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.tetronate_spirotetronate"),
    Cassette("MMC-008", "Thioamide/YcaO cassette", "mamey_cassette", "thioamide_ycao", "TIER_1_DIAGNOSTIC", "HIGH", optional_markers=("MMK-DOM-013", "MMK-CCTT-009", "MMK-UMED-005"), targets=(Target("regex", r"thioamide|ycaO"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="YcaO/thioamide signal set for rare thioamidated peptide hypotheses.", positive_interpretation="High novelty cue, especially in NRPS/RiPP contexts.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.thioamide_ycao"),
    Cassette("MMC-009", "Lanthipeptide cassette", "mamey_cassette", "lanthipeptide", "TIER_2_CLASS_SUPPORTING", "MODERATE", optional_markers=("MMK-CCTT-007", "MMK-UMED-001", "MMK-UMED-002", "MMK-UMED-004"), targets=(Target("regex", r"lanthipeptide|lanm|lanc|lant|lanp"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), description="Lanthipeptide/RiPP biosynthesis and maturation signal set.", positive_interpretation="Supports lanthipeptide lead status when precursor and maturation logic are visible.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.lanthipeptide"),
    Cassette("MMC-010", "Lasso peptide cassette", "mamey_cassette", "lassopeptide", "TIER_1_DIAGNOSTIC", "HIGH", optional_markers=("MMK-CCTT-008",), targets=(Target("regex", r"lassopeptide|lasso peptide"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Lasso-peptide signal set.", positive_interpretation="High-confidence RiPP cue when lasso maturation constellation is confirmed.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.lassopeptide"),
    Cassette("MMC-011", "TOMM/azole RiPP cassette", "mamey_cassette", "tomm_azole_ripp", "TIER_1_DIAGNOSTIC", "HIGH", optional_markers=("MMK-DOM-013", "MMK-UMED-006"), targets=(Target("regex", r"azole|tomm|cyclodehydratase|dehydrogenase|ripp"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), description="Azol(in)e-containing RiPP/TOMM signal set.", positive_interpretation="High MRSA-track cue when precursor, YcaO/cyclodehydratase, and oxidation logic are concordant.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.tomm_azole_ripp"),
    Cassette("MMC-012", "Polyene/PTM/HSAF cassette", "mamey_cassette", "polyene_ptm_hsaf", "TIER_1_DIAGNOSTIC", "HIGH", optional_markers=("MMK-CCTT-012",), targets=(Target("regex", r"polyene|hsaf|maltophilin|tetramate|pks-nrps"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "antifungal_fractionation"), description="Polyene tetramate/HSAF-like PKS-NRPS signal set.", positive_interpretation="Strong Candida/antifungal-track cue when PKS-NRPS architecture is confirmed.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.polyene_ptm_hsaf"),
    Cassette("MMC-013", "Siderophore/metallophore cassette", "mamey_cassette", "siderophore_metallophore", "TIER_2_CLASS_SUPPORTING", "MODERATE", optional_markers=("MMK-REG-010",), targets=(Target("regex", r"siderophore|metallophore|nrp-metallophore|iron|ferric"),), wet_lab_routes=("ecology_assay", "lcms_msms", "hmm_blast_confirm"), description="Iron/metal acquisition signal set.", positive_interpretation="Supports siderophore/metallophore ecology and CAS/metal-limitation assays.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.siderophore_metallophore"),
    Cassette("MMC-014", "Transporter/resistance cassette", "mamey_cassette", "transporter_resistance", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", optional_markers=("MMK-DOM-019", "MMK-RES-006"), targets=(Target("regex", r"transporter|efflux|exporter|resistance|immunity"),), wet_lab_routes=("inventory_only",), description="Export, efflux, resistance, or immunity wording near BGCs.", positive_interpretation="Supportive only; never proves activity or self-protection without class-specific concordance.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.transporter_resistance"),
    Cassette("MMC-015", "Chitin/glycan ecology cassette", "mamey_cassette", "chitin_glycan_ecology", "TIER_2_CLASS_SUPPORTING", "MODERATE", optional_markers=("MMK-CGAD-001", "MMK-CGAD-002", "MMK-CGAD-003", "MMK-CGAD-004", "MMK-CGAD-005"), targets=(Target("regex", r"chitinase|gh18|gh19|aa10|lpmo|glcnac|dasr"),), wet_lab_routes=("ecology_assay", "tfbs_induction", "hmm_blast_confirm"), description="Chitinolysis, GlcNAc response, and glycan-active ecology signal set.", positive_interpretation="Supports antifungal/ecology hypotheses when full-proteome scope is confirmed.", source_locator="mamey/source_scans.py:CASSETTE_PATTERNS.chitin_glycan_ecology"),
)

validate_stable_ids(MAMEY_CASSETTES, "MMC-")

MAMEY_CASSETTE_BY_ID = {c.id: c for c in MAMEY_CASSETTES}
MAMEY_CASSETTE_BY_NAME = {c.name: c for c in MAMEY_CASSETTES}
