"""Sapote cassette registry draft.

Composite cassette records built from Sapote monolith marker-addenda and current
Mamey source-derived scan families.  These are intended as governed, stable
compound-class/claim-routing units for the next release.
"""
# ============================================================================
# RELEASE 2 SCOPE — REGISTRY IS DESCRIPTIVE, NOT YET A SCANNING BACKEND
# ----------------------------------------------------------------------------
# These Marker/Cassette objects formalise the detection vocabulary (names,
# Pfam accessions, evidence tiers, claim ceilings) but the Pfam/HMM-profile
# SCANNING they describe does NOT run in the current pipeline. Live detection
# happens in mamey/source_scans.py (regex) and mamey/antismash_evidence.py
# (GBK sec_met_domain Pfam extraction). The Pfam accessions below are targets
# for the Release 2 HMMER/Diamond backend, not active scan rules today.
# Do not treat presence of a Marker here as evidence that its Pfam profile
# was run against the proteome.
# ============================================================================

from __future__ import annotations

from .registry_schema import Cassette, Target, validate_stable_ids

SAPOTE_CASSETTES: tuple[Cassette, ...] = (
    Cassette("SMC-001", "Peptidyl-nucleoside antifungal cassette", "sapote_cassette", "peptidyl_nucleoside", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-NUC-001",), optional_markers=("SMK-RIPP-001",), targets=(Target("manual", "NikJ/PolH-like marker plus nucleoside BGC context"),), wet_lab_routes=("antifungal_fractionation", "lcms_msms", "hmm_blast_confirm"), description="Nikkomycin/polyoxin-like nucleoside logic cassette for Candida/antifungal prioritization.", positive_interpretation="Elevates Candida-forward leads and LC-MS/MS review for nucleoside-like features.", source_locator="mamey/sapote_markers.py; docs/SAPOTE_SLIM_JUDGMENT_KERNEL.md"),
    Cassette("SMC-002", "Phosphonate/self-protection cassette", "sapote_cassette", "phosphonate", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-PHO-001",), optional_markers=("MMK-RES-005",), targets=(Target("manual", "PepM/Pep mutase plus optional FomA/FomB self-protection"),), wet_lab_routes=("antibacterial_fractionation", "lcms_msms", "hmm_blast_confirm"), description="Phosphonate capacity with optional class-concordant self-protection.", positive_interpretation="Strong antibacterial/antimetabolite lead when PepM and self-protection are proximal.", source_locator="mamey/sapote_markers.py diagnostic markers; mamey/source_scans.py"),
    Cassette("SMC-003", "Enediyne safety cassette", "sapote_cassette", "enediyne", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-ENE-001",), targets=(Target("manual", "ene_KS/enediyne cassette plus self-protection hallmark review"),), wet_lab_routes=("safety_cytotoxicity", "lcms_msms", "hmm_blast_confirm"), description="Enediyne detection and safety-routing cassette.", positive_interpretation="Retains high lead priority while forcing cytotoxicity and self-protection review.", source_locator="mamey/sapote_markers.py diagnostic markers"),
    Cassette("SMC-004", "Aminocyclitol/aminoglycoside cassette", "sapote_cassette", "aminocyclitol", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-AMC-001",), optional_markers=("MMK-RES-004",), targets=(Target("manual", "DOIS/BtrC marker with aminoglycoside/aminocyclitol context"),), wet_lab_routes=("antibacterial_fractionation", "lcms_msms", "hmm_blast_confirm"), description="Aminocyclitol/aminoglycoside-class biosynthetic cassette.", positive_interpretation="Routes to antibacterial prioritization and aminoglycoside-like metabolomics.", source_locator="mamey/sapote_markers.py diagnostic markers"),
    Cassette("SMC-005", "RiPP production-capacity cassette", "sapote_cassette", "RiPP", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-RIPP-001",), optional_markers=("SMK-UMED-001", "SMK-UMED-002", "SMK-UMED-003", "SMK-UMED-004"), targets=(Target("manual", "credible RiPP precursor plus class-relevant maturation enzyme"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), description="Composite RiPP cassette requiring precursor and maturation logic.", positive_interpretation="Permits stronger RiPP production-capacity language than maturation or precursor evidence alone.", source_locator="mamey/sapote_markers.py UMED / RiPP rules"),
    Cassette("SMC-006", "Flavin-halogenation cassette", "sapote_cassette", "halogenation", "TIER_2_CLASS_SUPPORTING", "MODERATE", required_markers=("SMK-HAL-001",), optional_markers=("SMK-XHAL-001",), targets=(Target("manual", "flavin/FAD-dependent halogenase in BGC context"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Halogenation cassette for halogenated natural-product potential.", positive_interpretation="Raises priority for isotope-pattern and MS/MS review, but requires substrate and subclass confirmation.", source_locator="mamey/sapote_markers.py marker addenda"),
    Cassette("SMC-007", "XDA/SN2 organohalogen cassette", "sapote_cassette", "organohalogen", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-XHAL-001",), targets=(Target("manual", "SalL/FlA-like SAM-dependent halogenase plus adjacent PNP"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Organohalogen building-block cassette for XDA/SN2-like chemistry.", positive_interpretation="High novelty cue when the enzyme pair and neighborhood context are confirmed.", source_locator="mamey/sapote_markers.py marker addenda"),
    Cassette("SMC-008", "N-N bond/diazo cassette", "sapote_cassette", "N-N_diazo", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-NN-001",), targets=(Target("manual", "CreE plus CreD-like N-N/diazo biosynthetic pair"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "safety_cytotoxicity"), description="N-N bond/diazo/azoxy cassette.", positive_interpretation="High novelty and safety-aware lead cue when CreE/CreD-like pair is present.", source_locator="mamey/sapote_markers.py marker addenda"),
    Cassette("SMC-009", "Tetronate/spirotetronate cassette", "sapote_cassette", "tetronate_spirotetronate", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-TET-001",), targets=(Target("manual", "FkbH-like glyceryl transferase plus dedicated ACP"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Tetronate/spirotetronate building-block cassette.", positive_interpretation="Strong polyketide-tailoring cue when paired with pathway context.", source_locator="mamey/sapote_markers.py marker addenda"),
    Cassette("SMC-010", "Nitrile-installation cassette", "sapote_cassette", "nitrile", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-NIT-001",), optional_markers=("SMK-NIT-002",), targets=(Target("manual", "ArtA ASS-like nitrile synthetase with optional CalN context"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Nitrile-installation cassette.", positive_interpretation="High-value tailoring cue when ArtA-like evidence is confirmed.", source_locator="mamey/sapote_markers.py marker addenda"),
    Cassette("SMC-011", "Oxidative biaryl/dimerization cassette", "sapote_cassette", "oxidative_tailoring", "TIER_3_CONTEXT_TAILORING", "LOW", optional_markers=("SMK-BBE-001", "SMK-BIARYL-001"), targets=(Target("manual", "BBE-like or NmrA-family oxidoreductase with scaffold-compatible context"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Oxidative tailoring/dimerization context cassette.", positive_interpretation="Suggests complex oxidative tailoring but should not drive compound-class claims alone.", source_locator="mamey/sapote_markers.py marker addenda"),
    Cassette("SMC-012", "Lasso peptide constellation cassette", "sapote_cassette", "lasso_peptide", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-LASSO-001",), targets=(Target("manual", "lasso cyclase + protease + RRE/precursor constellation"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Composite lasso-peptide production cassette.", positive_interpretation="High-confidence lasso-RiPP cue when the constellation is intact.", source_locator="mamey/sapote_markers.py marker addenda"),
    Cassette("SMC-013", "Thioamitide/thioamide cassette", "sapote_cassette", "thioamide", "TIER_1_DIAGNOSTIC", "HIGH", required_markers=("SMK-THA-001",), targets=(Target("manual", "YcaO plus TfuA pair in RiPP/peptide context"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Thioamidated peptide/thioamitide cassette.", positive_interpretation="High novelty rare-peptide cue; particularly important in MRSA-forward peptide leads.", source_locator="mamey/sapote_markers.py marker addenda"),
    Cassette("SMC-014", "Lanthipeptide maturation cassette", "sapote_cassette", "lanthipeptide", "TIER_2_CLASS_SUPPORTING", "MODERATE", optional_markers=("SMK-UMED-001", "SMK-UMED-002", "SMK-UMED-004"), targets=(Target("manual", "lanthipeptide precursor/maturase/protease or trans-acting maturase model"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "antibacterial_fractionation"), description="Lanthipeptide maturation cassette with UMED-aware claim ceilings.", positive_interpretation="Supports lanthipeptide follow-up while preserving maturation-gap caveats.", source_locator="mamey/sapote_markers.py UMED"),
    Cassette("SMC-015", "Cluster-situated regulator cassette", "sapote_cassette", "regulatory", "TIER_2_CLASS_SUPPORTING", "MODERATE", optional_markers=("SMK-CSR-001", "SMK-CSR-002", "SMK-CSR-003", "SMK-CSR-004", "SMK-CSR-005"), targets=(Target("manual", "CSR family member within or adjacent to BGC"),), wet_lab_routes=("tfbs_induction",), description="Pathway-regulatory cassette for activation planning.", positive_interpretation="Routes candidate to regulator-aware fermentation/induction planning.", source_locator="mamey/sapote_markers.py CSR rules"),
    Cassette("SMC-016", "Self-protection concordance cassette", "sapote_cassette", "self_protection", "TIER_2_CLASS_SUPPORTING", "MODERATE", optional_markers=("SMK-RES-001", "SMK-TRN-001"), targets=(Target("manual", "class-concordant target duplication/resistance within proximity rule; HGT guard passed"),), wet_lab_routes=("hmm_blast_confirm", "genetic_validation"), description="Class-concordant self-protection cassette.", positive_interpretation="Can raise lead priority and claim confidence only when proximity and HGT guard criteria pass.", source_locator="mamey/sapote_markers.py resistance/self-protection rules"),
    Cassette("SMC-017", "Watchlist aryl-C-glycoside cassette", "sapote_watchlist_cassette", "watchlist", "TIER_3_CONTEXT_TAILORING", "LOW", optional_markers=("SMK-WATCH-001",), targets=(Target("manual", "aryl-C-glycoside polyketide watchlist context"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Watchlist cassette retained for future marker development.", positive_interpretation="Inventory as a candidate only; no strong claims.", source_locator="mamey/sapote_markers.py watchlist"),
    Cassette("SMC-018", "Watchlist corallorazine cassette", "sapote_watchlist_cassette", "watchlist", "TIER_3_CONTEXT_TAILORING", "LOW", optional_markers=("SMK-WATCH-002",), targets=(Target("manual", "corallorazine-like watchlist context"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm"), description="Watchlist cassette retained for future marker development.", positive_interpretation="Inventory as a candidate only; no strong claims.", source_locator="mamey/sapote_markers.py watchlist"),
    Cassette("SMC-019", "Watchlist azinomycin/genotoxin cassette", "sapote_watchlist_cassette", "watchlist", "TIER_3_CONTEXT_TAILORING", "LOW", optional_markers=("SMK-WATCH-003",), targets=(Target("manual", "azinomycin/genotoxin-like watchlist context"),), wet_lab_routes=("lcms_msms", "hmm_blast_confirm", "safety_cytotoxicity"), description="Safety-aware watchlist cassette retained for future marker development.", positive_interpretation="Inventory and safety flag only; no strong claims.", source_locator="mamey/sapote_markers.py watchlist"),
)

validate_stable_ids(SAPOTE_CASSETTES, "SMC-")

SAPOTE_CASSETTE_BY_ID = {c.id: c for c in SAPOTE_CASSETTES}
SAPOTE_CASSETTE_BY_NAME = {c.name: c for c in SAPOTE_CASSETTES}
