"""Sapote diagnostic marker registry draft.

This file promotes stable marker records from the Sapote monolith marker addenda
and judgment-kernel concepts.  These entries are not intended to replace the
full Sapote prose rules; they provide machine-readable hooks for validation,
claim ceilings, workbook propagation, and future HMM-backed scanning.

v9.7.202 (provenance repoint): every Marker below now cites `source_locator=
"mamey/sapote_markers.py ..."` — pointing at the implementing code, since the
formerly-cited `docs/SAPOTE_v8.10.2_MONOLITH.md` is not shipped in this bundle.
The design monolith (`docs/SAPOTE_MAMEY_BUNDLE_MONOLITH.md`, tracked separately
against bundle v9.7.6) remains the parent design controller, but the runtime
provenance of these rules is the code that enforces them. The active,
authoritative definition of each marker is the Marker(...) record itself plus
the corresponding scan rule in `mamey/source_scans.py`.
"""
# ============================================================================
# RELEASE 2 SCOPE — REGISTRY IS DESCRIPTIVE, NOT YET A SCANNING BACKEND
# ----------------------------------------------------------------------------
# These Marker/Cassette objects formalise the detection vocabulary (names,
# Pfam accessions, evidence tiers, claim ceilings) but the Pfam/HMM-profile
# SCANNING they describe does NOT run in the current pipeline. Live detection
# happens in mamey/source_scans.py (regex) and mamey/antismash_evidence.py
# (GBK sec_met_domain Pfam extraction). The Pfam accessions below are targets
# for the Release 2 HMMER/Diamond backend, not active scan rules today.
# Do not treat presence of a Marker here as evidence that its Pfam profile
# was run against the proteome.
# ============================================================================

from __future__ import annotations

from .registry_schema import Marker, Target, validate_stable_ids

SAPOTE_MARKERS: tuple[Marker, ...] = (
    Marker("SMK-NUC-001", "NikJ/PolH-like radical-SAM peptidyl-nucleoside enzyme", "sapote_marker_addenda", "peptidyl nucleoside", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"NikJ|PolH|radical.?SAM.*nucleoside|peptidyl.?nucleoside"), Target("hmm", "NikJ/PolH-like radical SAM PN profile", note="draft HMM target; add calibrated cutoff after profile build")), ("antifungal_fractionation", "lcms_msms", "hmm_blast_confirm"), "High-value marker for nikkomycin/polyoxin-like peptidyl-nucleoside logic.", "Routes to Candida/antifungal track and nucleoside LC-MS review.", source_locator="mamey/sapote_markers.py marker addenda; glossary v1.2"),
    Marker("SMK-PHO-001", "PepM phosphoenolpyruvate mutase", "sapote_marker_addenda", "phosphonate", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"PepM|phosphoenolpyruvate mutase|PEP mutase"), Target("pfam", "PF13714", note="PepM family varies by annotation; confirm with HMM/BLAST")), ("antibacterial_fractionation", "lcms_msms", "hmm_blast_confirm"), "Committed phosphonate biosynthesis marker.", "High-confidence phosphonate clue when paired with pathway context and optional FomA/FomB.", source_locator="mamey/sapote_markers.py diagnostic markers"),
    Marker("SMK-ENE-001", "ene_KS / enediyne PKS cassette", "sapote_marker_addenda", "enediyne", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"ene.?KS|enediyne.*ketosynthase|enediyne PKS"), Target("hmm", "ene_KS curated profile", note="draft target")), ("safety_cytotoxicity", "lcms_msms", "hmm_blast_confirm"), "Defining enediyne biosynthetic marker.", "Requires cytotoxicity/safety caution and self-protection/hallmark-gene review.", source_locator="mamey/sapote_markers.py diagnostic markers"),
    Marker("SMK-AMC-001", "DOIS/BtrC 2-deoxy-scyllo-inosose synthase", "sapote_marker_addenda", "aminocyclitol", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"DOIS|BtrC|2-deoxy-scyllo-inosose|aminocyclitol synthase"),), ("antibacterial_fractionation", "lcms_msms", "hmm_blast_confirm"), "Committed aminocyclitol/aminoglycoside biosynthetic marker.", "Routes to aminoglycoside-like antibacterial follow-up when context is concordant.", source_locator="mamey/sapote_markers.py diagnostic markers"),
    Marker("SMK-RIPP-001", "RiPP maturation enzyme plus credible precursor", "sapote_marker_addenda", "RiPP", "TIER_1_DIAGNOSTIC", "HIGH", (Target("manual", "RiPP maturation enzyme + credible precursor peptide", required_context="co-located or proximal within BGC"),), ("lcms_msms", "hmm_blast_confirm"), "Composite RiPP capacity marker requiring both precursor and maturation logic.", "Stronger than either precursor or maturation enzyme alone.", source_locator="mamey/sapote_markers.py diagnostic markers"),
    Marker("SMK-HAL-001", "Flavin-dependent halogenase", "sapote_marker_addenda", "halogenation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"flavin-dependent halogenase|tryptophan halogenase|FAD-dependent halogenase"),), ("lcms_msms", "hmm_blast_confirm"), "Halogenated natural-product tailoring marker.", "Requires substrate-class and isotope/MS confirmation for claims.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-TRN-001", "Generic ABC/MFS transporter", "sapote_marker_addenda", "transport", "TIER_5_OVERINTERPRETATION_RISK", "INVENTORY_ONLY", (Target("regex", r"ABC transporter|MFS transporter|major facilitator"),), ("inventory_only",), "Generic transporter marker retained only for context.", "Never class-confirming or activity-confirming by itself.", source_locator="mamey/sapote_markers.py claim-safety rules"),
    Marker("SMK-RES-001", "Duplicated target/resistance gene near BGC", "sapote_marker_addenda", "self-protection", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("manual", "duplicated target or resistance gene within BGC/proximity rule"),), ("hmm_blast_confirm", "genetic_validation"), "Self-protection hypothesis marker when class-concordant and proximity/HGT guards pass.", "Supports Lead Priority more than Claim Confidence unless mechanism is specific.", source_locator="mamey/sapote_markers.py resistance/self-protection rules"),
    Marker("SMK-XHAL-001", "SalL/FlA SAM-dependent halogenase plus PNP", "sapote_marker_addenda", "XDA organohalogen", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"SalL|FlA|fluorinase|chlorinase|SAM-dependent halogenase|purine nucleoside phosphorylase|PNP"),), ("lcms_msms", "hmm_blast_confirm"), "Organohalogen building-block marker set for XDA/SN2-like chemistry.", "High novelty cue when the SAM-dependent halogenase and adjacent PNP context are confirmed.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-NN-001", "CreE plus CreD N-N/diazo cassette", "sapote_marker_addenda", "N-N/diazo", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"CreE|CreD|diazo|azoxy|hydrazine|N-N bond"),), ("lcms_msms", "hmm_blast_confirm", "safety_cytotoxicity"), "N-N bond/diazo biosynthesis marker pair.", "High novelty and safety-aware follow-up when both CreE and CreD-like evidence are present.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-TET-001", "FkbH-like glyceryl transferase plus dedicated ACP", "sapote_marker_addenda", "tetronate/spirotetronate", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"FkbH|glyceryl transferase|dedicated ACP|tetronate|spirotetronate"),), ("lcms_msms", "hmm_blast_confirm"), "Tetronate/spirotetronate biosynthetic marker set.", "Strong only with FkbH-like enzyme and dedicated ACP/context.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-NIT-001", "ArtA ASS-like nitrile synthetase", "sapote_marker_addenda", "nitrile installation", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"ArtA|argininosuccinate synthase-like|ASS-like nitrile synthetase|nitrile synthetase"),), ("lcms_msms", "hmm_blast_confirm"), "Nitrile-installation marker.", "High-value tailoring cue; requires pathway context and MS/MS support.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-NIT-002", "CalN SelO/YdiU-like pseudokinase", "sapote_marker_addenda", "nitrile context", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"CalN|SelO|YdiU|pseudokinase"),), ("hmm_blast_confirm",), "Context marker for nitrile-related biosynthetic logic.", "Context-only unless paired with stronger nitrile marker.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-BBE-001", "BBE-like FAD oxidoreductase", "sapote_marker_addenda", "oxidative tailoring", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"BBE-like|berberine bridge enzyme|FAD oxidoreductase"),), ("lcms_msms", "hmm_blast_confirm"), "Oxidative tailoring marker for complex scaffold formation.", "Not class-definitive alone.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-BIARYL-001", "NmrA-family oxidoreductase", "sapote_marker_addenda", "biaryl dimerization", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"NmrA|NmrA-family oxidoreductase|biaryl"),), ("lcms_msms", "hmm_blast_confirm"), "Possible oxidative biaryl-dimerization context marker.", "Context-only without scaffold and gene-neighborhood support.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-LASSO-001", "Lasso cyclase/protease/RRE constellation", "sapote_marker_addenda", "lasso peptide", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"PF00733|lasso cyclase|transglutaminase protease|RRE|RiPP recognition element"),), ("lcms_msms", "hmm_blast_confirm"), "Composite lasso peptide maturation constellation.", "High-confidence lasso cue when cyclase, protease, and RRE/precursor context co-occur.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-THA-001", "YcaO plus TfuA pair", "sapote_marker_addenda", "thioamitide/thioamide", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"YcaO|TfuA|thioamitide|thioamide"),), ("lcms_msms", "hmm_blast_confirm"), "Thioamide/thioamitide maturation marker pair.", "High novelty rare-peptide cue when both YcaO and TfuA-like evidence are concordant.", source_locator="mamey/sapote_markers.py marker addenda"),
    Marker("SMK-UMED-001", "LanP / Peptidase_S8", "sapote_umed", "RiPP maturation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"LanP|Peptidase_S8|subtilisin"),), ("lcms_msms", "hmm_blast_confirm"), "Lanthipeptide maturation protease marker.", "Supports production capacity only with precursor/maturase context.", source_locator="mamey/sapote_markers.py UMED"),
    Marker("SMK-UMED-002", "LanT / Peptidase_C39", "sapote_umed", "RiPP maturation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"LanT|Peptidase_C39|C39 peptidase"),), ("lcms_msms", "hmm_blast_confirm"), "Lanthipeptide processing/export marker.", "Supports maturation/export only with context.", source_locator="mamey/sapote_markers.py UMED"),
    Marker("SMK-UMED-003", "FlaP / AplP / Peptidase_S9", "sapote_umed", "RiPP maturation", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"FlaP|AplP|Peptidase_S9"),), ("lcms_msms", "hmm_blast_confirm"), "RiPP maturation protease marker.", "Context required.", source_locator="mamey/sapote_markers.py UMED"),
    Marker("SMK-UMED-004", "M16B metallopeptidase", "sapote_umed", "RiPP maturation", "TIER_1_DIAGNOSTIC", "HIGH", (Target("regex", r"M16B|M16 metallopeptidase|pitrilysin"), Target("pfam", "PF00675/PF05193", note="heterodimer guard required")), ("lcms_msms", "hmm_blast_confirm"), "M16B lanthipeptide maturation marker.", "High-value only when paired subunit/heterodimer guard passes.", source_locator="mamey/sapote_markers.py UMED"),
    Marker("SMK-CSR-001", "SARP", "sapote_csr", "cluster-situated regulator", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"SARP|Streptomyces antibiotic regulatory protein"),), ("tfbs_induction",), "Pathway activator/regulator marker.", "Supports activation model, not product identity.", source_locator="mamey/sapote_markers.py CSR rules"),
    Marker("SMK-CSR-002", "PAS-LuxR", "sapote_csr", "cluster-situated regulator", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"PAS-LuxR|PimM|LuxR"),), ("tfbs_induction",), "PAS-LuxR/PimM-like pathway-regulator marker.", "Supports activation model in macrolide/polyene contexts.", source_locator="mamey/sapote_markers.py CSR rules"),
    Marker("SMK-CSR-003", "Composite SARP-LAL", "sapote_csr", "cluster-situated regulator", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"SARP-LAL|PimR|LAL regulator"),), ("tfbs_induction",), "Composite regulatory cascade marker.", "Supports upper-tier activation model only.", source_locator="mamey/sapote_markers.py CSR rules"),
    Marker("SMK-CSR-004", "GBL receptor", "sapote_csr", "cluster-situated regulator", "TIER_2_CLASS_SUPPORTING", "MODERATE", (Target("regex", r"GBL receptor|ArpA|ScbR|gamma-butyrolactone receptor"),), ("tfbs_induction",), "Gamma-butyrolactone receptor/regulatory marker.", "Supports quorum-coupled expression model.", source_locator="mamey/sapote_markers.py CSR rules"),
    Marker("SMK-CSR-005", "Pseudo-GBL receptor", "sapote_csr", "cluster-situated regulator", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"pseudo-GBL|ScbR2|JadR2"),), ("tfbs_induction",), "Antibiotic-feedback/pseudo-GBL regulatory clue.", "Context-only unless pathway feedback is shown.", source_locator="mamey/sapote_markers.py CSR rules"),
    Marker("SMK-WATCH-001", "Aryl-C-glycoside polyketide watchlist", "sapote_watchlist", "watchlist", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"aryl-C-glycoside|C-glycoside polyketide"),), ("lcms_msms", "hmm_blast_confirm"), "Watchlist marker retained for future validation.", "Do not promote to strong claim without curated markers.", source_locator="mamey/sapote_markers.py watchlist"),
    Marker("SMK-WATCH-002", "Corallorazine watchlist", "sapote_watchlist", "watchlist", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"corallorazine"),), ("lcms_msms", "hmm_blast_confirm"), "Watchlist marker retained for future validation.", "Do not promote without curated marker set.", source_locator="mamey/sapote_markers.py watchlist"),
    Marker("SMK-WATCH-003", "Azinomycin-type genotoxin watchlist", "sapote_watchlist", "watchlist", "TIER_3_CONTEXT_TAILORING", "LOW", (Target("regex", r"azinomycin|aziridine|genotoxin"),), ("lcms_msms", "hmm_blast_confirm", "safety_cytotoxicity"), "Watchlist marker for azinomycin/genotoxin-like chemistry.", "Safety-aware only; no strong claim without curated markers.", source_locator="mamey/sapote_markers.py watchlist"),
)

validate_stable_ids(SAPOTE_MARKERS, "SMK-")

SAPOTE_MARKER_BY_ID = {m.id: m for m in SAPOTE_MARKERS}
SAPOTE_MARKER_BY_NAME = {m.name: m for m in SAPOTE_MARKERS}
