#!/usr/bin/env python3
"""Diagnose drift between this bundle's assistant contract and an explicitly configured mirror.

A development workspace often keeps a copy of `AGENTS.md` / `CLAUDE.md` at its root so an assistant
opening the workspace cold reads the operating contract. That copy is outside the bundle and is not
regenerated by a cut, so it goes stale silently -- a mirror has been observed sitting four cuts
behind while the bundle's own `render_bootstrap_contract.py --check` passed every time. The gate and
the file a reader actually opens were different files.

This tool reports that drift. It deliberately does NOT repair it, and it makes no assumption that a
bundle has a writable parent:

  * The mirror is **explicitly configured** -- `--mirror PATH` or `SAPOTE_INSTRUCTION_MIRROR`.
    Nothing is inferred from the bundle's parent directory. A standalone bundle with no mirror
    configured reports NOT_CONFIGURED and exits 0.
  * It **never writes**, inside the bundle or outside it. Repairing a development workspace is an
    explicit owner action, not a side effect of a check.
  * It is **advisory by default** (exit 0 even on drift). `--strict` makes drift exit 1, so an
    operator can opt in to a hard gate; release does not depend on external state unless someone
    deliberately asks it to.

Exit codes: 0 advisory/in-sync/not-configured; 1 drift under --strict; 2 usage/read error.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MIRRORED = ("AGENTS.md", "CLAUDE.md")
ENV_VAR = "SAPOTE_INSTRUCTION_MIRROR"

# --strict is an opt-in gate. A configured mirror that is absent or partial is at least as
# alarming as one that has drifted: it means the check has been passing against nothing.
# NOT_CONFIGURED stays exit 0 — a standalone bundle with no development workspace is not a
# failure, which is the documented default.
STRICT_FAIL_STATES = frozenset({"DRIFT", "MIRROR_MISSING", "INCOMPLETE"})


def _sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _resolve_mirror(arg: str | None) -> pathlib.Path | None:
    raw = arg or os.environ.get(ENV_VAR) or ""
    raw = raw.strip()
    return pathlib.Path(raw).expanduser() if raw else None


def diagnose(mirror: pathlib.Path | None, root: pathlib.Path = ROOT) -> dict:
    """Compare the bundle's contract surfaces against a configured mirror. Read-only."""
    if mirror is None:
        return {"status": "NOT_CONFIGURED", "mirror": None, "surfaces": [],
                "detail": f"no --mirror and no {ENV_VAR}; nothing to compare (this is not an error)"}
    if not mirror.is_dir():
        return {"status": "MIRROR_MISSING", "mirror": str(mirror), "surfaces": [],
                "detail": "configured mirror directory does not exist"}

    surfaces, drifted, missing = [], 0, 0
    for name in MIRRORED:
        src, dst = root / name, mirror / name
        if not src.is_file():
            surfaces.append({"surface": name, "state": "BUNDLE_SURFACE_MISSING"})
            missing += 1
            continue
        if not dst.is_file():
            surfaces.append({"surface": name, "state": "ABSENT_IN_MIRROR",
                             "bundle_sha256": _sha256(src)})
            missing += 1
            continue
        a, b = _sha256(src), _sha256(dst)
        state = "IN_SYNC" if a == b else "DRIFT"
        if state == "DRIFT":
            drifted += 1
        surfaces.append({"surface": name, "state": state,
                         "bundle_sha256": a, "mirror_sha256": b})

    if drifted:
        status = "DRIFT"
    elif missing:
        status = "INCOMPLETE"
    else:
        status = "IN_SYNC"
    return {"status": status, "mirror": str(mirror), "surfaces": surfaces,
            "detail": f"{drifted} drifted, {missing} missing of {len(MIRRORED)} surfaces"}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mirror", default=None,
                    help=f"directory holding the mirrored contract; else ${ENV_VAR}")
    ap.add_argument("--strict", action="store_true",
                    help="exit 1 on DRIFT (opt-in; never a release prerequisite)")
    ap.add_argument("--json", action="store_true", help="emit the report as JSON")
    a = ap.parse_args(argv)

    try:
        report = diagnose(_resolve_mirror(a.mirror))
    except OSError as exc:
        sys.stderr.write(f"INSTRUCTION_MIRROR_READ_ERROR: {exc}\n")
        return 2

    if a.json:
        sys.stdout.write(json.dumps(report, indent=2) + "\n")
    else:
        sys.stdout.write(f"instruction mirror: {report['status']} — {report['detail']}\n")
        for s in report["surfaces"]:
            sys.stdout.write(f"  {s['surface']:<12} {s['state']}\n")
        if report["status"] == "DRIFT":
            sys.stdout.write(
                "  the mirror is what an assistant opening the workspace reads; repairing it is an\n"
                "  explicit owner action, deliberately not performed here\n")

    return 1 if (a.strict and report["status"] in STRICT_FAIL_STATES) else 0


if __name__ == "__main__":
    raise SystemExit(main())
