#!/usr/bin/env python3
"""gen_user_catalog.py — generate the USER-FACING cassette + scan catalogs (v9.7.86 B4).

THE TRAP THIS CLOSES
--------------------
The workbook ships `Cassette_Registry`, `Regulators`, and `Transporters` sheets, but the
15 cassette families and the regulator/transporter scans had no documentation home: a user
reading `tomm_azole_ripp: 67` in their workbook had nowhere in the manual or encyclopedia to
learn what it means. Hand-writing those tables lets them rot. This tool generates them FROM
the scanner (`source_scans.CASSETTE_PATTERNS` + the enriched `registry_inventory` via the
hand-verified `CASSETTE_REGISTRY_MAP`), so the docs regenerate from code and `--check` fails
the build if the committed catalog drifts. The manual/encyclopedia INCLUDE the generated block.

    python3 tools/gen_user_catalog.py            # write docs/USER_CATALOG.generated.{md,json}
    python3 tools/gen_user_catalog.py --check    # exit 1 if the committed catalog is stale
"""
from __future__ import annotations

import os as _os, sys as _sys  # v9.7.407: resolve the tools-local emitter from any cwd
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from _console import emit  # noqa: E402

import hashlib
import json
import sys
import pathlib


def _read_json(_path, *, encoding="utf-8"):
    """P3b: context-managed JSON read; closes the handle a bare open() leaked."""
    import json as _json
    with open(_path, encoding=encoding) as _fh:
        return _json.load(_fh)


ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _wbio import atomic_write_text  # noqa: E402
MD_OUT = ROOT / "docs" / "USER_CATALOG.generated.md"
JSON_OUT = ROOT / "docs" / "USER_CATALOG.generated.json"


def _load_registry() -> dict:
    d = _read_json(ROOT / "registry_inventory_v1.9.4.json")
    lst = d if isinstance(d, list) else d.get("entries", d.get("inventory", []))
    return {e["id"]: e for e in lst if isinstance(e, dict) and "id" in e}


# The twelve workbook-surfacing scans, with claim-safe one-liners. The ten first-pass scans
# plus regulators + transporters (which emit their own sheets but fell outside "the ten").
SCAN_CATALOG = [
    ("KCB_sweep",   "Known-cluster-blast similarity sweep -> RiQ novelty. KCB is a similarity signal, not a product identification."),
    ("RG_GMCI",     "Reference-genome-guided multi-cluster integration: detects split-cluster pairs across contig breaks."),
    ("FLBR",        "Fragment-linked biosynthetic rescue / LMPKS fragment set."),
    ("CCTT",        "T43 diagnostic class triggers (15 families) feeding AB/AF/novelty."),
    ("CGAD",        "Chitinase / glycan-active-domain ecology scan."),
    ("UMED",        "RiPP maturation-machinery scan (proteases / transporters / maturation gaps)."),
    ("EFLS",        "Evidence-from-linkage scan: candidate co-localized pairs."),
    ("resistance",  "Self-protection / resistance-tier scan."),
    ("bldA_TTA",    "bldA-dependent TTA-codon developmental-control scan. NOT_APPLICABLE outside actinomycetes."),
    ("TFBS",        "Transcription-factor binding-site motif scan (upstream region)."),
    ("regulators",  "Regulator-family census (cluster-situated + global regulators)."),
    ("transporters","Transporter-family census (ABC / MFS / efflux)."),
]


def build_catalog() -> dict:
    from mamey.source_scans import CASSETTE_PATTERNS, CASSETTE_REGISTRY_MAP
    reg = _load_registry()

    cassettes = []
    for family in CASSETTE_PATTERNS:
        mmc = CASSETTE_REGISTRY_MAP.get(family, "")
        entry = reg.get(mmc, {})
        cassettes.append({
            "family": family,
            "registry_id": mmc,
            "name": entry.get("name", ""),
            "tier": entry.get("tier", ""),
            "detects": ", ".join(CASSETTE_PATTERNS[family]),
            "description": entry.get("description", ""),
            "positive_interpretation": entry.get("positive_interpretation", ""),
            "negative_interpretation": entry.get("negative_interpretation", ""),
            "claim_safety": entry.get("claim_safety", ""),
        })

    scans = [{"scan": s, "description": d} for s, d in SCAN_CATALOG]
    return {"cassettes": cassettes, "scans": scans}


def render_md(cat: dict) -> str:
    lines = []
    lines.append("<!-- GENERATED by tools/gen_user_catalog.py — do not edit by hand. -->")
    lines.append("<!-- Regenerate: python3 tools/gen_user_catalog.py ; verify: --check -->")
    lines.append("")
    lines.append("# The fifteen cassette families")
    lines.append("")
    lines.append("Cassette families are the biosynthetic-machinery census surfaced in the workbook "
                 "`Cassette_Registry` sheet. A cassette count is **capacity / signal, not product "
                 "or activity**; bioactivity is extract-level; absence of a family is **not** a "
                 "negative call. `siderophore_metallophore` and `transporter_resistance` are "
                 "widespread and low-discrimination.")
    lines.append("")
    for c in cat["cassettes"]:
        lines.append(f"## {c['family']}  ({c['registry_id']} — {c['name']})")
        if c["tier"]:
            lines.append(f"*Tier:* {c['tier']}")
        lines.append("")
        lines.append(f"**Detects (regex evidence):** {c['detects']}")
        lines.append("")
        if c["description"]:
            lines.append(c["description"])
            lines.append("")
        if c["positive_interpretation"]:
            lines.append(f"*Positive:* {c['positive_interpretation']}")
        if c["negative_interpretation"]:
            lines.append(f"*Negative:* {c['negative_interpretation']}")
        if c["claim_safety"]:
            lines.append(f"*Claim-safety:* {c['claim_safety']}")
        lines.append("")
    lines.append("# The twelve workbook scans")
    lines.append("")
    lines.append("The ten first-pass scans plus the regulator and transporter context scans "
                 "(each emits its own workbook sheet).")
    lines.append("")
    for s in cat["scans"]:
        lines.append(f"- **{s['scan']}** — {s['description']}")
    lines.append("")
    return "\n".join(lines)


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def main():
    check = "--check" in sys.argv
    cat = build_catalog()
    md = render_md(cat)
    js = json.dumps(cat, indent=2, ensure_ascii=False)

    if check:
        stale = []
        for path, content in ((MD_OUT, md), (JSON_OUT, js)):
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.name)
        if stale:
            emit("USER_CATALOG out of sync (regenerate with gen_user_catalog.py): "
                  + ", ".join(stale))
            sys.exit(1)
        emit(f"USER_CATALOG OK ({len(cat['cassettes'])} cassettes, {len(cat['scans'])} scans)")
        return

    # v9.7.374: bare Path.write_text() calls -- a process killed mid-write left a truncated
    # docs/USER_CATALOG.generated.{md,json} on disk. atomic_write_text (tmp+os.replace) is the
    # same crash-safe helper already used elsewhere in this codebase for exactly this write
    # pattern (see tools/_wbio.py's own docstring on the BadZipFile/truncation hazard).
    atomic_write_text(MD_OUT, md)
    atomic_write_text(JSON_OUT, js)
    emit(f"wrote {MD_OUT.name} + {JSON_OUT.name} "
          f"({len(cat['cassettes'])} cassettes, {len(cat['scans'])} scans, digest {_digest(md)})")


if __name__ == "__main__":
    main()
