#!/usr/bin/env python3
"""gen_tools_inventory.py — list every tool, so nobody rebuilds one that exists (W22-adjacent).

THE PROBLEM THIS CLOSES
-----------------------
tools/ holds ~70 scripts. With no index, a contributor (human or LLM) cannot see what
already exists and rebuilds it — which is exactly how a redundant public-cut / tier-parity /
judgment-receipt tool got written. This generator reads the one-line summary out of every
tool's docstring/header and:
  * writes docs/TOOLS_INVENTORY.generated.md (the full table), and
  * injects a compact `name — summary` list into SESSION_START_MANIFEST.md between
    managed markers, so the session-start menu actually lists the toolbox.

`--check` fails the build if either is stale, so the index can't drift from tools/.

    python3 tools/gen_tools_inventory.py            # write inventory + inject into manifest
    python3 tools/gen_tools_inventory.py --check     # exit 1 if stale
"""
from __future__ import annotations

import os as _os, sys as _sys  # v9.7.407: resolve the tools-local emitter from any cwd
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from _console import emit  # noqa: E402

import ast
import argparse
import csv
try:  # v9.7.410 CSV formula-cell guard (CLAUDE_v9.7.410_tools_csv_writer_coverage)
    from mamey.csv_safety import SafeDictWriter as _SafeDictWriter, SafeWriter as _SafeWriter
except ImportError:  # bare-script run: bundle root is one level up
    import os as _cs_os, sys as _cs_sys
    _cs_sys.path.insert(0, _cs_os.path.dirname(_cs_os.path.dirname(_cs_os.path.abspath(__file__))))
    from mamey.csv_safety import SafeDictWriter as _SafeDictWriter, SafeWriter as _SafeWriter
import hashlib
import json
import re
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _wbio import atomic_write_text  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"
MD_OUT = ROOT / "docs" / "TOOLS_INVENTORY.generated.md"
MANIFEST = ROOT / "SESSION_START_MANIFEST.md"
START = "<!-- TOOLS_INVENTORY:START (generated by tools/gen_tools_inventory.py — do not edit) -->"
END = "<!-- TOOLS_INVENTORY:END -->"

CONNECTION_SCHEMA_VERSION = "tool_connections_v1"
_TOOL_NAME_RE = re.compile(r"(?<![A-Za-z0-9_.-])([A-Za-z0-9_][A-Za-z0-9_.-]*\.(?:py|sh))(?![A-Za-z0-9_.-])")
_IMPORT_RE = re.compile(r"(?:^|\n)\s*(?:from|import)\s+([A-Za-z_][A-Za-z0-9_.]*)", re.MULTILINE)
_MAC_USER_ROOT = "/" + "Us" + "ers/"
_WINDOWS_USER_ROOT = "\\" + "Us" + "ers\\"
_PERSONAL_PATH_RE = re.compile(
    r"(?:"
    + re.escape(_MAC_USER_ROOT)
    + r"[A-Za-z0-9][A-Za-z0-9._-]*/|[A-Za-z]:"
    + re.escape(_WINDOWS_USER_ROOT)
    + r"[A-Za-z0-9][A-Za-z0-9._-]*\\)"
)
_NETWORK_RE = re.compile(
    r"\b(?:requests\.|urllib\.request|Bio\.Entrez|Entrez\.|curl\b|https?://|ncbi\b)",
    re.IGNORECASE,
)
_HISTORICAL_DOC_PARTS = {
    "archive", "archives", "batches", "historical", "legacy", "patch_notes",
}
_GENERATED_DOCS = {
    "TOOLS_INVENTORY.generated.md",
    "USER_CATALOG.generated.md",
}

# Query-side vocabulary stays with the inventory owner; it is not a second tool registry.
# These four concepts are the measured blind spot that motivated the active search surface.
_CAPABILITY_TERM_EXPANSIONS = {
    "split": ("fragment", "contig", "rescue", "reconstruction", "rggmci"),
    "fragment": ("split", "contig", "rescue", "reconstruction", "rggmci"),
    "contig": ("split", "fragment", "rescue", "reconstruction", "rggmci"),
    "rescue": ("split", "fragment", "contig", "reconstruction", "rggmci"),
}


def _module_docstring_py(path: pathlib.Path) -> str:
    """Return one module docstring through the inventory's canonical AST parser."""
    try:
        mod = ast.parse(path.read_text(encoding="utf-8"))
        return ast.get_docstring(mod) or ""
    except Exception:
        return ""


def _first_doc_line_py(path: pathlib.Path) -> str:
    doc = _module_docstring_py(path)
    if not doc:
        return "(no docstring)"
    line = next((l.strip() for l in doc.splitlines() if l.strip()), "(no docstring)")
    # strip a leading "name.py — " prefix so the summary isn't redundant
    if "—" in line:
        line = line.split("—", 1)[1].strip()
    elif " - " in line and line.lower().startswith(path.name.lower()):
        line = line.split(" - ", 1)[1].strip()
    # v9.7.410 hostile audit: the summary lands in a markdown table cell; a `|` in a docstring
    # split the row into extra columns and corrupted the generated inventory.
    return line.replace("|", "\\|")


def _first_doc_line_sh(path: pathlib.Path) -> str:
    for raw in path.read_text(encoding="utf-8").splitlines():
        s = raw.strip()
        if s.startswith("#!"):
            continue
        if s.startswith("#"):
            s = s.lstrip("# ").strip()
            if not s:
                continue
            if "—" in s:
                s = s.split("—", 1)[1].strip()
            return s
    return "(no header comment)"


def collect() -> list[tuple[str, str]]:
    rows = []
    for p in sorted(TOOLS.iterdir()):
        if p.is_dir() or p.name.startswith("."):
            continue
        if p.suffix == ".py":
            rows.append((p.name, _first_doc_line_py(p)))
        elif p.suffix == ".sh":
            rows.append((p.name, _first_doc_line_sh(p)))
    # include top-level bootstrap.sh if present (env setup lives at root)
    boot = ROOT / "bootstrap.sh"
    if boot.exists():
        rows.append(("../bootstrap.sh", _first_doc_line_sh(boot)))
    return rows


def _capability_modules(root: pathlib.Path):
    """Yield the Python modules covered by the portable internal-capability surface."""
    for dirname in ("tools", "mamey"):
        directory = root / dirname
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*.py")):
            if not path.name.startswith("__"):
                yield path


def expand_capability_terms(keywords) -> list[str]:
    """Normalize query terms and add only the owner's bounded retrieval aliases."""
    terms = []
    for keyword in keywords:
        term = str(keyword).strip().lower()
        if term and term not in terms:
            terms.append(term)
        for expansion in _CAPABILITY_TERM_EXPANSIONS.get(term, ()):
            if expansion not in terms:
                terms.append(expansion)
    return terms


def search_capabilities(keywords, root: pathlib.Path = ROOT, top: int = 10) -> list[dict]:
    """Search full module docstrings without creating a second capability registry.

    Ranking first rewards coverage of distinct query terms, then total occurrences,
    with the relative path as a deterministic tie-break.  Results expose the matched
    lines and a run hint only when the existing interface detector finds an entrypoint.
    """
    root = pathlib.Path(root).resolve()
    terms = expand_capability_terms(keywords)
    if not terms or top < 1:
        return []

    results = []
    for path in _capability_modules(root):
        doc = _module_docstring_py(path)
        lowered = doc.lower()
        # ROSTER_402 seed #3: the module NAME is a capability signal too. The query
        # "rggmci" missed mamey/rggmci.py itself (its docstring spells "RG-GMCI"),
        # while ten other modules that merely MENTION rggmci surfaced — the owner was
        # the one invisible file. Count a stem hit as one occurrence; docstring
        # occurrences still dominate ranking via total count.
        stem = path.stem.lower()
        counts = {}
        for term in terms:
            occurrences = lowered.count(term)
            if term in stem:
                occurrences += 1
            if occurrences:
                counts[term] = occurrences
        if not counts:
            continue
        text = _read_text(path)
        summary = _first_doc_line_py(path)
        interface, _, _ = _interface_and_lifecycle(path, text, summary)
        relative = path.relative_to(root)
        if interface == "PYTHON_CLI":
            run_hint = f"python {relative} --help"
        elif interface == "PYTHON_ENTRYPOINT":
            run_hint = f"python {relative}"
        else:
            run_hint = ""
        matched_lines = [
            line.strip() for line in doc.splitlines()
            if line.strip() and any(term in line.lower() for term in counts)
        ]
        if any(term in stem for term in counts):
            matched_lines.insert(0, f"(module name: {path.name})")
        results.append({
            "path": str(relative),
            "summary": summary,
            "matched_keywords": list(counts),
            "matched_keyword_count": len(counts),
            "stem_match_count": sum(1 for term in counts if term in stem),
            "match_count": sum(counts.values()),
            "matched_lines": matched_lines[:4],
            "run_hint": run_hint,
        })
    # seed #3 ranking: a module whose NAME matches the query is the likely owner and
    # outranks modules that merely mention the term in prose; docstring coverage and
    # occurrence totals still order everything else, path stays the deterministic tie-break.
    results.sort(key=lambda row: (
        -row["matched_keyword_count"], -row["stem_match_count"],
        -row["match_count"], row["path"]
    ))
    return results[:top]


def capabilities_command(keywords, root: pathlib.Path = ROOT, top: int = 10) -> int:
    """Print deterministic, offline concept-search results for internal modules."""
    hits = search_capabilities(keywords, root=root, top=top)
    query = [str(keyword).strip().lower() for keyword in keywords if str(keyword).strip()]
    terms = expand_capability_terms(query)
    suffix = f" (expanded: {terms})" if terms != query else ""
    # composer note (.401): report writes via sys.stdout.write per the ratchet convention
    # (sealed .400 sits exactly at the 1635 ceiling; the report legitimately belongs on stdout).
    out = sys.stdout.write
    out(f"capabilities: full-docstring search for {query}{suffix}\n")
    if not hits:
        out("  no matches; try broader terms or inspect docs/TOOLS_INVENTORY.generated.md\n")
        return 0
    for index, hit in enumerate(hits, 1):
        out(
            f"\n{index}. {hit['path']} "
            f"({hit['matched_keyword_count']} keyword(s), {hit['match_count']} occurrence(s))\n"
        )
        out(f"   {hit['summary']}\n")
        for line in hit["matched_lines"]:
            out(f"     | {line[:110]}\n")
        if hit["run_hint"]:
            out(f"   run: {hit['run_hint']}\n")
    out("\nCheck these BEFORE writing a new tool.\n")
    return 0


def _read_text(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _strip_managed_inventory(text: str) -> str:
    """Remove the generated all-tools block so it cannot self-certify discoverability."""
    if START not in text or END not in text:
        return text
    before, rest = text.split(START, 1)
    _, after = rest.split(END, 1)
    return before + after


def _corpus_files(root: pathlib.Path, kind: str) -> list[pathlib.Path]:
    if kind == "tests":
        return sorted((root / "tests").rglob("*.py")) if (root / "tests").exists() else []
    if kind == "source":
        files = []
        if (root / "mamey").exists():
            files.extend((root / "mamey").rglob("*.py"))
        if (root / "tools").exists():
            files.extend((root / "tools").glob("*.py"))
        top = root / "mamey_run.py"
        if top.exists():
            files.append(top)
        return sorted(files)
    if kind == "docs":
        files = []
        for name in (
            "README.md", "README_START_HERE.md", "SESSION_START_MANIFEST.md",
            "CURRENT_DOCS_INDEX.md", "COMMANDS.md",
        ):
            path = root / name
            if path.exists():
                files.append(path)
        if (root / "docs").exists():
            for path in (root / "docs").rglob("*.md"):
                rel_parts = {part.lower() for part in path.relative_to(root / "docs").parts[:-1]}
                if rel_parts & _HISTORICAL_DOC_PARTS or path.name in _GENERATED_DOCS:
                    continue
                files.append(path)
        return sorted(set(files))
    if kind == "manifests":
        return [
            path for path in (
                root / "MODULE_MANIFEST.txt",
                root / "TIER_MANIFEST.txt",
                root / "SOURCE_CHECKSUMS_SHA256.txt",
            ) if path.exists()
        ]
    raise ValueError(f"unknown corpus kind: {kind}")


def _reference_index(root: pathlib.Path, tool_names: set[str], kind: str) -> dict[str, set[str]]:
    refs = {name: set() for name in tool_names}
    stems = {pathlib.Path(name).stem: name for name in tool_names if name.endswith(".py")}
    for path in _corpus_files(root, kind):
        text = _read_text(path)
        if path.name == "SESSION_START_MANIFEST.md":
            text = _strip_managed_inventory(text)
        names = set(_TOOL_NAME_RE.findall(text)) & tool_names
        if path.suffix == ".py":
            imported_stems = {module.split(".")[-1] for module in _IMPORT_RE.findall(text)}
            names.update(stems[stem] for stem in imported_stems if stem in stems)
        locator = str(path.relative_to(root))
        for name in names:
            refs[name].add(locator)
    return refs


def _interface_and_lifecycle(path: pathlib.Path, text: str, summary: str) -> tuple[str, str, str]:
    lifecycle = "ACTIVE_OR_UNSPECIFIED"
    declared = summary.lower()
    if "deprecated" in declared or "retired" in declared:
        lifecycle = "DECLARED_DEPRECATED_OR_RETIRED"
    elif "one-off" in declared or "one off" in declared or "frozen cohort" in declared:
        lifecycle = "DECLARED_ONE_OFF_OR_FROZEN"

    if path.suffix == ".sh":
        return "SHELL_ENTRYPOINT", lifecycle, ""
    try:
        tree = ast.parse(text)
    except SyntaxError as exc:
        return "AST_PARSE_HOLD", lifecycle, f"{exc.msg} at line {exc.lineno}"
    has_main_guard = any(
        isinstance(node, ast.If)
        and isinstance(node.test, ast.Compare)
        and isinstance(node.test.left, ast.Name)
        and node.test.left.id == "__name__"
        and any(isinstance(op, ast.Eq) for op in node.test.ops)
        and any(isinstance(value, ast.Constant) and value.value == "__main__" for value in node.test.comparators)
        for node in ast.walk(tree)
    )
    has_cli_lib = any(token in text for token in ("argparse", "click.", "typer."))
    if has_main_guard and has_cli_lib:
        return "PYTHON_CLI", lifecycle, ""
    if has_main_guard:
        return "PYTHON_ENTRYPOINT", lifecycle, ""
    return "IMPORT_ONLY_OR_HELPER", lifecycle, ""


def _scores(*, interface: str, lifecycle: str, cli_n: int, source_n: int,
            test_n: int, doc_n: int, manifest_n: int, has_summary: bool) -> tuple[int, int]:
    """Return transparent evidence scores; these do not measure scientific importance."""
    interconnection = min(100, sum((
        25 if cli_n else 0,
        25 if source_n else 0,
        20 if test_n else 0,
        15 if doc_n else 0,
        10 if manifest_n else 0,
        5 if interface != "IMPORT_ONLY_OR_HELPER" else 0,
    )))
    utility = min(100, sum((
        20 if interface not in {"IMPORT_ONLY_OR_HELPER", "AST_PARSE_HOLD"} else 0,
        25 if test_n else 0,
        20 if doc_n else 0,
        25 if (cli_n or source_n) else 0,
        10 if has_summary else 0,
    )))
    if lifecycle != "ACTIVE_OR_UNSPECIFIED":
        utility = max(0, utility - 20)
    return interconnection, utility


def audit_connections(root: pathlib.Path = ROOT) -> dict:
    """Build a deterministic connection and operational-utility evidence register."""
    root = root.resolve()
    tools_dir = root / "tools"
    rows = []
    paths = sorted(
        path for path in tools_dir.iterdir()
        if path.is_file() and not path.name.startswith(".") and path.suffix in {".py", ".sh"}
    )
    bootstrap = root / "bootstrap.sh"
    if bootstrap.exists():
        paths.append(bootstrap)
        paths.sort()
    names = {path.name for path in paths}
    refs = {kind: _reference_index(root, names, kind) for kind in ("tests", "source", "docs", "manifests")}

    cli_paths = {"mamey/cli.py", "mamey_run.py"}
    for path in paths:
        text = _read_text(path)
        summary = _first_doc_line_py(path) if path.suffix == ".py" else _first_doc_line_sh(path)
        interface, lifecycle, parse_error = _interface_and_lifecycle(path, text, summary)
        source_refs = refs["source"][path.name] - {str(path.relative_to(root))}
        cli_refs = source_refs & cli_paths
        non_cli_source_refs = source_refs - cli_paths
        test_refs = refs["tests"][path.name]
        doc_refs = refs["docs"][path.name]
        manifest_refs = refs["manifests"][path.name]
        interconnection, utility = _scores(
            interface=interface,
            lifecycle=lifecycle,
            cli_n=len(cli_refs),
            source_n=len(non_cli_source_refs),
            test_n=len(test_refs),
            doc_n=len(doc_refs),
            manifest_n=len(manifest_refs),
            has_summary=summary not in {"(no docstring)", "(no header comment)"},
        )
        personal_path = bool(_PERSONAL_PATH_RE.search(text))
        network_capability = bool(_NETWORK_RE.search(text))

        if parse_error:
            disposition = "AST_PARSE_HOLD"
        elif personal_path:
            disposition = "PERSONAL_PATH_LITERAL_REVIEW"
        elif lifecycle != "ACTIVE_OR_UNSPECIFIED":
            disposition = "DECLARED_LEGACY_REVIEW"
        elif test_refs and (cli_refs or non_cli_source_refs or doc_refs):
            disposition = "CONNECTED_AND_TESTED"
        elif (cli_refs or non_cli_source_refs or doc_refs) and not test_refs:
            disposition = "CONNECTED_UNTESTED"
        elif test_refs:
            disposition = "TESTED_STANDALONE"
        elif interface not in {"IMPORT_ONLY_OR_HELPER", "AST_PARSE_HOLD"}:
            disposition = "STANDALONE_UNDISCOVERED_REVIEW"
        else:
            disposition = "UNREFERENCED_HELPER_REVIEW"

        rows.append({
            "tool": path.name,
            "path": str(path.relative_to(root)),
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "bytes": path.stat().st_size,
            "summary": summary,
            "interface": interface,
            "lifecycle": lifecycle,
            "cli_reference_files": sorted(cli_refs),
            "source_reference_files": sorted(non_cli_source_refs),
            "test_reference_files": sorted(test_refs),
            "documentation_reference_files": sorted(doc_refs),
            "manifest_reference_files": sorted(manifest_refs),
            "personal_path_literal": personal_path,
        "external_contact_marker": network_capability,
            "interconnection_score": interconnection,
            "operational_utility_evidence_score": utility,
            "disposition": disposition,
            "parse_error": parse_error,
        })

    return {
        "schema_version": CONNECTION_SCHEMA_VERSION,
        "root_role": "portable_project_root",
        "tool_count": len(rows),
        "score_contract": {
            "interconnection_score": "CLI 25 + non-CLI source 25 + tests 20 + path-filtered non-historical docs 15 + manifests 10 + executable interface 5; capped at 100",
            "operational_utility_evidence_score": "executable interface 20 + tests 25 + path-filtered non-historical docs 20 + source/CLI consumer 25 + summary 10 - declared legacy 20; bounded 0..100",
            "claim_ceiling": "Evidence of wiring and operational support only; not scientific value, correctness, acceptance, or release authority.",
        },
        "tools": rows,
    }


def render_connections_tsv(payload: dict) -> str:
    columns = [
        "tool", "path", "sha256", "bytes", "interface", "lifecycle",
        "interconnection_score", "operational_utility_evidence_score", "disposition",
        "cli_reference_files", "source_reference_files", "test_reference_files",
        "documentation_reference_files", "manifest_reference_files",
        "personal_path_literal", "external_contact_marker", "summary", "parse_error",
    ]
    from io import StringIO
    buffer = StringIO()
    writer = _SafeDictWriter(buffer, fieldnames=columns, delimiter="\t", lineterminator="\n")
    writer.writeheader()
    for row in payload["tools"]:
        cooked = dict(row)
        for key in (
            "cli_reference_files", "source_reference_files", "test_reference_files",
            "documentation_reference_files", "manifest_reference_files",
        ):
            cooked[key] = "|".join(cooked[key])
        writer.writerow({key: cooked[key] for key in columns})
    return buffer.getvalue()


def _truncate(s: str, n: int = 110) -> str:
    return s if len(s) <= n else s[: n - 1] + "…"


def render_md(rows) -> str:
    out = ["# Tools Inventory (generated)", "",
           f"**{len(rows)} tools** in `tools/`. Generated from each tool's docstring by "
           "`tools/gen_tools_inventory.py` — do not edit by hand. Check this list BEFORE "
           "writing a new tool.", "",
           "> **This is the INTERNAL script catalog** (the `tools/` helpers shipped with the "
           "engine). For the **external tool stack** the workflow depends on — antiSMASH, "
           "BiG-SCAPE, IQ-TREE, GToTree, BLAST+, SPAdes and their versions/citations — see "
           "`docs/EXTERNAL_TOOL_INVENTORY.md`.", "",
           "| Tool | What it does |", "|---|---|"]
    for name, desc in rows:
        out.append(f"| `{name}` | {_truncate(desc)} |")
    out.extend([
        "",
        "**Additional engine-internal CLI (in `mamey/`, not auto-inventoried):**",
        "",
        "| Tool | What it does |",
        "|---|---|",
        "| `mamey/workbook_schema_check.py` | Workbook schema validator. "
        "Run: `python -m mamey.workbook_schema_check [--fast|--full] [--v12] <workbook.xlsx>`. "
        "Returns PASS/FAIL JSON; exit 0 = PASS. Lives in `mamey/` so not picked up here (C3 fix). |",
    ])
    return "\n".join(out) + "\n"


def render_manifest_block(rows) -> str:
    lines = [START,
             f"### Tools inventory ({len(rows)} scripts in `tools/`)",
             "_Check here before building a new tool. Full table: `docs/TOOLS_INVENTORY.generated.md`._", ""]
    for name, desc in rows:
        lines.append(f"- `{name}` — {_truncate(desc, 90)}")
    lines.append(END)
    return "\n".join(lines)


def _reconcile_dirmap_count(text: str, n: int) -> str:
    """Keep the hand-written directory-map count (`tools/` (N scripts, ...)) in sync with the real tool
    count, so it cannot drift out of step with the generated inventory block below it."""
    import re
    return re.sub(r"(`tools/`\s*\()\d+(\s*scripts)", rf"\g<1>{n}\g<2>", text, count=1)


def inject(block: str, n: int | None = None) -> str:
    text = MANIFEST.read_text(encoding="utf-8")
    if n is not None:
        text = _reconcile_dirmap_count(text, n)
    if START in text and END in text:
        pre = text[: text.index(START)]
        post = text[text.index(END) + len(END):]
        return pre + block + post
    # append a fresh section
    return text.rstrip() + "\n\n---\n\n" + block + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify committed generated inventory")
    parser.add_argument("--connections", action="store_true", help="emit connection and utility evidence audit")
    parser.add_argument("--search", nargs="+", metavar="KEYWORD", help="search full internal-module docstrings")
    parser.add_argument("--top", type=int, default=10, help="maximum search results (default: 10)")
    parser.add_argument("--root", type=pathlib.Path, default=ROOT, help="project root for --connections/--search (default: bundle root)")
    parser.add_argument("--format", choices=("json", "tsv"), default="json", help="--connections output format")
    parser.add_argument("--output", type=pathlib.Path, help="atomically write --connections output instead of stdout")
    args = parser.parse_args(argv)
    if args.search:
        if args.top < 1:
            parser.error("--top must be at least 1")
        return capabilities_command(args.search, root=args.root, top=args.top)
    if args.connections:
        payload = audit_connections(args.root)
        if args.format == "json":
            content = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
        else:
            content = render_connections_tsv(payload)
        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            atomic_write_text(args.output, content)
        else:
            emit(content, end="")
        return 0

    rows = collect()
    md = render_md(rows)
    block = render_manifest_block(rows)
    if args.check:
        stale = []
        if not MD_OUT.exists() or MD_OUT.read_text(encoding="utf-8") != md:
            stale.append("docs/TOOLS_INVENTORY.generated.md")
        if MANIFEST.exists() and (START not in MANIFEST.read_text(encoding="utf-8")
                                  or block not in MANIFEST.read_text(encoding="utf-8")):
            stale.append("SESSION_START_MANIFEST.md inventory block")
        if MANIFEST.exists():
            _mt = MANIFEST.read_text(encoding="utf-8")
            if _reconcile_dirmap_count(_mt, len(rows)) != _mt:
                stale.append("SESSION_START_MANIFEST.md directory-map tool count")
        if stale:
            emit("TOOLS INVENTORY STALE — regenerate with gen_tools_inventory.py:\n  "
                  + "\n  ".join(stale))
            return 1
        emit(f"tools inventory OK — {len(rows)} tools, manifest in sync")
        return 0
    MD_OUT.parent.mkdir(parents=True, exist_ok=True)
    # v9.7.374: bare Path.write_text() calls -- a process killed mid-write left a truncated
    # docs/TOOLS_INVENTORY.generated.md, or worse, a truncated SESSION_START_MANIFEST.md (the
    # session-start menu itself). atomic_write_text (tmp+os.replace) is the same crash-safe
    # helper already used elsewhere in this codebase for exactly this write pattern.
    atomic_write_text(MD_OUT, md)
    if MANIFEST.exists():
        atomic_write_text(MANIFEST, inject(block, len(rows)))
    emit(f"wrote inventory: {len(rows)} tools; injected block into SESSION_START_MANIFEST.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
