#!/usr/bin/env python3
"""regen_modeb_contract_docs.py — regenerate Mode B contract docs from the JSON.

Reads `mamey/data/mode_b/modeb_full30_corrective_contract.json` (the single
source of truth for §1–§30) and emits two markdown documents:

  - `docs/MODE_B_30_SECTION_CANONICAL_TITLES.md`
      Section-titles-only doc — for chats and humans browsing the contract.

  - `docs/FULL_MODEB_30_SECTION_CONTRACT_v97150.md`
      Full contract spec — required/conditional, predicate descriptions,
      quality-gate checklist.

These docs were previously handwritten alongside the JSON. Drift between
contract data and contract docs is the failure mode N10 documented after the
v9.7.150d cut showed six §1–§20 schema sources in the bundle. This tool
collapses that surface to one: edit the JSON, run the regen, commit both.

Usage:
    python3 tools/regen_modeb_contract_docs.py
        # regenerates both docs in place

    python3 tools/regen_modeb_contract_docs.py --check
        # exits 0 if both docs match what would be generated; 1 if drift
        # exists. Use in CI to enforce "JSON is source of truth."

    python3 tools/regen_modeb_contract_docs.py --titles-out <path>
                                                --contract-out <path>
        # write to non-default locations (for testing)

W9-C / N10 (v9.7.150e+).
"""
from __future__ import annotations

import os as _os, sys as _sys  # v9.7.407: resolve the tools-local emitter from any cwd
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from _console import emit  # noqa: E402
import argparse
import difflib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _wbio import atomic_write_text  # noqa: E402

# Resolved relative to the bundle root (this file lives in tools/)
_BUNDLE_ROOT = Path(__file__).resolve().parent.parent
_DEFAULT_CONTRACT = _BUNDLE_ROOT / "mamey" / "data" / "mode_b" / "modeb_full30_corrective_contract.json"
_DEFAULT_TITLES_DOC = _BUNDLE_ROOT / "docs" / "MODE_B_30_SECTION_CANONICAL_TITLES.md"
_DEFAULT_CONTRACT_DOC = _BUNDLE_ROOT / "docs" / "FULL_MODEB_30_SECTION_CONTRACT_v97150.md"


def load_contract(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"Contract JSON not found at {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise ValueError(f"Contract JSON malformed: {e}") from e


# ---------------------------------------------------------------------------
# Markdown generators
# ---------------------------------------------------------------------------

def render_titles_doc(contract: dict) -> str:
    """Render the canonical titles doc — section names + a compact required/
    conditional summary."""
    sv = contract.get("schema_version", "?")
    sections = sorted(contract.get("sections", []), key=lambda s: s["number"])

    lines = [
        f"# Mode B canonical section titles — §1–§30 (`{sv}`)",
        "",
        "> **Generated from `mamey/data/mode_b/modeb_full30_corrective_contract.json` by "
        "`tools/regen_modeb_contract_docs.py`. Do not edit this file by hand — "
        "edit the JSON and re-run the regen tool.**",
        "",
        "## One-line rule",
        "",
        "**These are the canonical titles for the legacy `MODEB_CANDIDATE_30` profile** "
        "(v9.7.372 named-profile rule: never the unqualified word 'full' — finished "
        "deliverables use the `FINISHED_FULL48_CURRENT_EVIDENCE` profile, §§1–48 exactly "
        "once and in order). Within `MODEB_CANDIDATE_30`: §1–§20 always required, in "
        "numeric order. §28 + §30 also always required. §21–§27 and §29 are conditional — "
        "required when the BGC matches the predicate (see "
        "`FULL_MODEB_30_SECTION_CONTRACT_v97150.md` for the full table). LLMs, renderers, "
        "and validators must not invent, rename, reorder, or substitute sections.",
        "",
        "## Named profiles (v9.7.372)",
        "",
        *[f"- **`{name}`** — {desc}" for name, desc in (contract.get("profiles") or {}).items()],
        "",
        "## Always required (§1–§20, §28, §30)",
        "",
    ]

    always = [s for s in sections if s.get("required") == "always"]
    for s in always:
        lines.append(f"{s['number']}. **{s['title']}**")

    cond = [s for s in sections if s.get("required") == "conditional"]
    if cond:
        lines.extend([
            "",
            "## Conditional (§21–§27, §29)",
            "",
            "Required when the named predicate fires for this BGC. Omit otherwise.",
            "",
            "| § | Title | Required when |",
            "|---|---|---|",
        ])
        for s in cond:
            lines.append(
                f"| {s['number']} | **{s['title']}** | {s.get('condition_human','—')} |"
            )

    lines.extend([
        "",
        "## Non-negotiable schema rules",
        "",
        "- §7 is **Transport, resistance, and regulation**.",
        "- §16 is **BLASTP/HMMER next steps**.",
        "- §28 (Evidence provenance ledger) and §30 (Experimental decision tree) are mandatory.",
        "- A section named `Manual BLASTP evidence, if present` is obsolete and must fail "
        "the current Full Mode B validator.",
        "- Older `§1–§8`, `§1–§10`, and prior 20-title inventories are historical/scaffold "
        "contracts only; they are not current Full Mode B.",
        "",
        "## Artifact-drift rule",
        "",
        "A real Mode B card is a written interpretation built from evidence. Tables, "
        "FASTA files, PDFs, character counts, and before/after trackers are supporting "
        "artifacts, not acceptance evidence. One BGC must pass the prose-first gate "
        "before scaling to many BGCs.",
        "",
        "## Source of truth",
        "",
        f"This document is generated from `mamey/data/mode_b/"
        f"modeb_full30_corrective_contract.json` (schema `{sv}`). The validator "
        f"`mamey.modeb_structure_gate.lint_card()` and the template emitter "
        f"`mamey emit-modeb-template` both read the JSON directly. The §1–§20 facade "
        f"`mamey.validators.modeb_full20` derives its sections list from the same "
        f"JSON. There is **one** §1–§30 schema source in the bundle.",
        "",
    ])
    return "\n".join(lines) + "\n"


def render_contract_doc(contract: dict) -> str:
    """Render the full contract spec — section policy, predicates, quality
    gate, complete required/conditional table."""
    sv = contract.get("schema_version", "?")
    superseded = contract.get("supersedes", "—")
    section_policy = contract.get("section_policy", "")
    quality_gate = contract.get("quality_gate", []) or []
    sections = sorted(contract.get("sections", []), key=lambda s: s["number"])

    lines = [
        f"# Full Mode B §1–§30 Contract (`{sv}`)",
        "",
        "> **Generated from `mamey/data/mode_b/modeb_full30_corrective_contract.json` by "
        "`tools/regen_modeb_contract_docs.py`. Do not edit this file by hand — "
        "edit the JSON and re-run the regen tool.**",
        "",
        f"**Schema version:** `{sv}`  ",
        f"**Supersedes:** {superseded}  ",
        f"**Source protocol:** {contract.get('source_protocol', '—')}",
        "",
        "## Section policy",
        "",
        f"{section_policy}",
        "",
        "## Named profiles (v9.7.372)",
        "",
        *[f"- **`{name}`** — {desc}" for name, desc in (contract.get("profiles") or {}).items()],
        *([f"", f"{contract['profile_note']}"] if contract.get("profile_note") else []),
        "",
        "## Sections — required/conditional table",
        "",
        "| § | Title | Required | Condition |",
        "|---|---|---|---|",
    ]
    for s in sections:
        req = s.get("required", "?")
        cond = s.get("condition_human", "—") if req == "conditional" else "—"
        lines.append(f"| {s['number']} | **{s['title']}** | {req} | {cond} |")

    # Conditional predicates summary
    cond_sections = [s for s in sections if s.get("required") == "conditional"]
    if cond_sections:
        lines.extend([
            "",
            "## Conditional predicates",
            "",
            "Each conditional section is gated by a named predicate evaluated against the "
            "BGC's context (triage row + strain rollups). The validator "
            "(`mamey.modeb_structure_gate.lint_card`) and template emitter "
            "(`mamey emit-modeb-template`) use the same predicate set, defined in "
            "`mamey/modeb_structure_gate.py::_build_predicates`.",
            "",
            "| § | Predicate key | Triggers when |",
            "|---|---|---|",
        ])
        for s in cond_sections:
            lines.append(
                f"| {s['number']} | `{s.get('condition_key','—')}` | "
                f"{s.get('condition_human','—')} |"
            )

    # Section sub-questions (LQ-MODEB-02): deepen an existing section with named prompts the
    # author theorises over. Additive to the §1-§30 structure — no new section, no gate change.
    sq_sections = [s for s in sections if s.get("sub_questions")]
    if sq_sections:
        lines.extend([
            "",
            "## Section sub-questions",
            "",
            "Named prompts that deepen an existing section (no new section is added). The template "
            "emitter renders them for the author; the depth gate treats them as WARN-only.",
            "",
        ])
        for s in sq_sections:
            lines.append(f"**§{s['number']} — {s['title']}**")
            for q in s["sub_questions"]:
                lines.append(f"- {q}")
            lines.append("")

    # Quality gate
    if quality_gate:
        lines.extend([
            "",
            "## Quality gate",
            "",
            "Every completed Mode B card must satisfy these checks. The validator "
            "enforces (1) and (2)–(3) structurally; the rest are content-level checks "
            "the chat is responsible for satisfying.",
            "",
        ])
        for i, line in enumerate(quality_gate, start=1):
            lines.append(f"{i}. {line}")

    # Artifact-drift policy
    drift = contract.get("artifact_drift_policy") or {}
    if drift:
        lines.extend([
            "",
            "## Artifact-drift policy",
            "",
        ])
        for k, v in drift.items():
            lines.append(f"- **`{k}`:** {v}")

    lines.extend([
        "",
        "## Single source of truth (W9-C / N10)",
        "",
        f"Before v9.7.150e there were six §1–§20 schema sources in the bundle (two JSON "
        f"files, a hard-coded fallback in `mamey/modeb_structure_gate.py`, an archival "
        f"legacy JSON, and two handwritten markdown docs). N10 collapsed that surface: "
        f"`modeb_full30_corrective_contract.json` is now the **only** §1–§30 schema. "
        f"This document and `MODE_B_30_SECTION_CANONICAL_TITLES.md` are generated by "
        f"`tools/regen_modeb_contract_docs.py`. The `mamey/modeb_structure_gate.py` "
        f"facade derives its §1–§20 sections via "
        f"`mamey.modeb_structure_gate.load_contract()`. Run "
        f"`tools/regen_modeb_contract_docs.py --check` in CI to enforce no drift.",
        "",
    ])
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _diff(label: str, expected: str, got: str) -> str:
    return "".join(difflib.unified_diff(
        expected.splitlines(keepends=True),
        got.splitlines(keepends=True),
        fromfile=f"{label} (expected)",
        tofile=f"{label} (on disk)",
        n=3,
    ))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--contract", default=str(_DEFAULT_CONTRACT),
                    help="Path to the source contract JSON (default: bundled).")
    ap.add_argument("--titles-out", default=str(_DEFAULT_TITLES_DOC),
                    help="Path for the canonical titles doc (default: docs/...).")
    ap.add_argument("--contract-out", default=str(_DEFAULT_CONTRACT_DOC),
                    help="Path for the full contract doc (default: docs/...).")
    ap.add_argument("--check", action="store_true",
                    help="Exit 0 if both docs match what would be generated; "
                         "exit 1 with a diff if drift exists. Use in CI.")
    args = ap.parse_args(argv)

    try:
        contract = load_contract(Path(args.contract))
    except (FileNotFoundError, ValueError) as e:
        emit(f"ERROR: {e}", file=sys.stderr)
        return 1

    titles_md = render_titles_doc(contract)
    contract_md = render_contract_doc(contract)

    if args.check:
        drift = False
        for path_str, expected in (
            (args.titles_out, titles_md),
            (args.contract_out, contract_md),
        ):
            p = Path(path_str)
            on_disk = p.read_text(encoding="utf-8") if p.exists() else ""
            if on_disk != expected:
                drift = True
                emit(_diff(p.name, expected, on_disk))
                if not p.exists():
                    emit(f"  (file does not exist: {p})")
        if drift:
            emit("\nDRIFT DETECTED. Run `tools/regen_modeb_contract_docs.py` to "
                  "regenerate, then commit both.", file=sys.stderr)
            return 1
        emit("Mode B contract docs match the JSON contract: NO DRIFT.")
        return 0

    # v9.7.374 (audit lane): a crash/kill mid-write must never leave a truncated
    # contract doc on disk (the failure mode this session found and fixed repeatedly
    # elsewhere) — write via the shared atomic .tmp+os.replace helper, not a bare
    # write_text().
    Path(args.titles_out).parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(args.titles_out, titles_md)
    emit(f"wrote {args.titles_out}")
    Path(args.contract_out).parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(args.contract_out, contract_md)
    emit(f"wrote {args.contract_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
