#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(ape);library(ggtree);library(ggplot2);library(patchwork)})
a<-commandArgs(trailingOnly=TRUE);if(length(a)==0)a<-'both';stopifnot(length(a)==1,a[1]%in%c('concise','experiment_id','both'));variant<-a[1]
script<-sub('^--file=','',grep('^--file=',commandArgs(),value=TRUE)[1]);if(!file.exists(script))script<-gsub('~+~',' ',script,fixed=TRUE);setwd(dirname(normalizePath(script)))
# Required default: both label variants. `Rscript render_placement_COLOR_STRIPS.R` (or `... both`) renders the
# concise figure and the experiment-ID figure; naming one variant renders only that one.
if(variant=='both'){for(v in c('concise','experiment_id')){st<-system2('Rscript',c(shQuote(script),v));if(st!=0)stop('variant failed: ',v)};quit(status=0)}
tr<-read.tree('tree_input.newick');original<-tr;md<-read.delim('metadata.tsv',quote='',check.names=FALSE,na.strings=character(),colClasses='character');out<-readLines('outgroup.txt',warn=FALSE);excluded<-readLines('exclude_tips.txt',warn=FALSE);excluded<-excluded[nzchar(excluded)]
if(length(out)&&nzchar(out[1])){stopifnot(out[1]%in%tr$tip.label);tr<-root(tr,outgroup=out[1],resolve.root=TRUE)}
if(length(excluded)){stopifnot(all(excluded%in%tr$tip.label));tr<-drop.tip(tr,excluded)}
stopifnot(!anyDuplicated(md$tip),setequal(md$tip,tr$tip.label),all(nzchar(md$source_category)),all(nzchar(md$geography_category)))
# Require exactly the retained source tip distances, even where rooting/pruning is needed.
z<-cophenetic(original)[md$tip,md$tip];zz<-cophenetic(tr)[md$tip,md$tip];stopifnot(max(abs(z-zz))<1e-8)
write.tree(tr,'tree_display.newick')
query<-md$role=='query';md$display<-md$label
if(variant=='experiment_id'){bound<-query&nzchar(md$sample_id);md$display[bound]<-paste0(md$display[bound],' {',md$sample_id[bound],'}')}
p<-ggtree(tr,ladderize=TRUE,size=.35);d<-p$data[p$data$isTip,];ix<-match(d$label,md$tip);d$text<-md$display[ix];d$query<-query[ix];d$source<-md$source_category[ix];d$geo<-md$geography_category[ix];d$Candida<-ifelse(d$query,md$Candida[ix],'');d$MRSA<-ifelse(d$query,md$MRSA[ix],'')
source_palette<-c('Bumblebee'='#0072B2','Honeybee'='#E69F00','Other bee'='#56B4E9','Wasp'='#CC79A7','Ant'='#882255','Attine'='#882255','Beehive pollen'='#AA7700','Bryophyte'='#44AA99','Lichen'='#AA4499','Lichen-moss mixture'='#DDCC77','Soil'='#8C510A','Plant-associated'='#228833','Marine-associated'='#332288','Mangrove'='#117733','Freshwater-associated'='#88CCEE','Freshwater sediment'='#88CCEE','Salt lake'='#999933','Animal-associated'='#D55E00','Animal/clinical'='#D55E00','Other documented'='#666666','Fungal-associated'='#AA3377','Built environment'='#999999','Rock-associated'='#999999','Coastal sediment'='#88AA99','Biofilter'='#A6761D','Termite'='#663399','Waste-associated'='#6B6B3D','Air-associated'='#BBBBBB')
geo_palette<-c('Africa'='#E69F00','Antarctica'='#56B4E9','Asia'='#CC79A7','Europe'='#332288','North America'='#44AA99','South America'='#D55E00','Oceania'='#882255','Europe / Asia'='#7B3294','Indian Ocean'='#999933','US'='#009E73','Canada'='#0072B2','Pacific Ocean'='#4477AA','Russia'='#A50F15','Turkey'='#F0E442','Virgin Islands'='#FB9A99','Costa Rica'='#B15928','Northern Cyprus'='#6A3D9A')  # the last six match the core-genome renderer so one geography keeps one colour across both figure families
stopifnot(all(d$source%in%names(source_palette)),all(d$geo%in%names(geo_palette)))
n<-Ntip(tr);xmax<-max(p$data$x);yr<-c(-.6,n+.6);scale_width<-10^floor(log10(xmax/5));if(xmax/5/scale_width>=5)scale_width<-5*scale_width else if(xmax/5/scale_width>=2)scale_width<-2*scale_width
p<-p+geom_segment(data=d,aes(x=x,xend=xmax*1.01,y=y,yend=y),linetype='dotted',linewidth=.16,colour='grey75')+geom_treescale(x=0,y=0,width=scale_width,fontsize=3)+scale_x_continuous(limits=c(0,xmax*1.015),expand=c(0,0))+ylim(yr)+theme(plot.margin=margin(5,0,5,10))
nd<-p$data[!p$data$isTip,];value<-suppressWarnings(as.numeric(nd$label));nd<-nd[!is.na(value)&value>=70&value<=100,];if(nrow(nd))p<-p+geom_text(data=nd,aes(x=x,y=y,label=label),size=2.5,hjust=-.1,vjust=-.5,colour='grey35')
d$plot_label<-vapply(d$text,function(z){m<-regexpr('^[A-Z][a-z]+ (?:sp\\.|[a-z]+)',z,perl=TRUE);if(m[1]<0)return(encodeString(z,quote='"'));k<-attr(m,'match.length');paste0('italic(',encodeString(substr(z,1,k),quote='"'),')~',encodeString(trimws(substring(z,k+1)),quote='"'))},character(1))
q<-ggplot(d,aes(x=0,y=y))+geom_text(aes(label=plot_label,colour=query),parse=TRUE,hjust=0,size=3.4)+scale_colour_manual(values=c('FALSE'='#202124','TRUE'='#bb0000'),guide='none')+scale_x_continuous(limits=c(0,1),expand=c(0,0))+ylim(yr)+theme_void()+theme(plot.margin=margin(5,4,5,3))
mk<-function(field,title,pal){ggplot(d,aes(x=0,y=y,fill=.data[[field]]))+geom_tile(width=.85,height=.96)+scale_fill_manual(values=pal[sort(unique(d[[field]]))],name=title)+ylim(yr)+theme_void()+labs(title=title)+theme(plot.title=element_text(size=9,hjust=.5),legend.position='bottom',legend.text=element_text(size=8),legend.title=element_text(size=9),plot.margin=margin(5,1,5,1))+guides(fill=guide_legend(ncol=5))}
act<-function(field,title){ggplot(d,aes(x=0,y=y))+geom_text(aes(label=.data[[field]]),size=4.2,fontface='bold')+ylim(yr)+theme_void()+labs(title=title)+theme(plot.title=element_text(size=9,hjust=.5,face='bold'),plot.margin=margin(5,1,5,1))}
pdf(NULL);label_inches<-max(vapply(d$text,function(z)grid::convertWidth(grid::grobWidth(grid::textGrob(z,gp=grid::gpar(fontsize=3.4*72.27/25.4))),'inches',valueOnly=TRUE),numeric(1)))+.4;dev.off()
branch_inches<-if(n>100)9 else 7.5;with_activity<-any(nzchar(d$Candida)|nzchar(d$MRSA));widths<-c(branch_inches,label_inches,.75,.75)
parts<-list(p,q,mk('source','Isolation\nsource',source_palette),mk('geo','Geography',geo_palette))
if(with_activity){parts<-c(parts,list(act('Candida','Candida\nInhibition'),act('MRSA','MRSA\ninhibition')));widths<-c(widths,.8,.8)}
fig<-wrap_plots(parts,widths=widths,nrow=1,guides='collect')&theme(legend.position='bottom')
stem<-paste0('EPAng_',basename(getwd()),'_R04_',variant);height<-max(5,2+n*.30);width<-sum(widths)+.4
# Full-tree exports retain row spacing; use vector PDF for zooming dense parent panels.
ggsave(paste0(stem,'.pdf'),fig,width=width,height=height,limitsize=FALSE)
ggsave(paste0(stem,'.png'),fig,width=width,height=height,dpi=if(n>150)140 else 200,limitsize=FALSE)
write.table(data.frame(tip=d$label,y=d$y,label=d$text,source=d$source,geography=d$geo,source_colour=unname(source_palette[d$source]),geography_colour=unname(geo_palette[d$geo]),Candida=d$Candida,MRSA=d$MRSA),paste0(stem,'_display_audit.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
write.table(data.frame(check=c('tip_metadata_bijection','retained_pairwise_branch_distances','source_category_palette','geography_category_palette'),status='PASS'),paste0(stem,'_validation.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
og<-if(length(out)&&nzchar(out[1]))out[1] else '';og_note<-if(!nzchar(og))'The tree is drawn as given in tree_input.newick.' else if(og%in%excluded)sprintf('Rooted on %s, the registry outgroup, which is then omitted from the display because it lacks a source or geography category (see OMITTED_TIPS.tsv where present).',og) else sprintf('Rooted on %s (registry outgroup).',og)
caption<-sprintf('16S rRNA EPA-ng placement of %d query tips with %d reference/outgroup tips. %s Topology and pairwise branch distances among the displayed tips are those of tree_input.newick, checked after rooting and pruning; %d tips listed in exclude_tips.txt are omitted. Branch lengths are substitutions per site. Numeric node support values of 70 or greater are shown where the input tree carries them; their inference method is the one recorded for that tree and is not reclassified. Query tips are red. Source and geography colours use the same mapping across panels; the category of each tip and its provenance (deposited record, culture collection or species description) are in the metadata provenance table beside this figure. Type marks NCBI 16S RefSeq targeted-loci records curated from type material. Inhibition calls, where available, are shown exactly as recorded on query rows; reference cells are blank. Experiment identifiers are appended only where documented; %d query tips lack a documented experiment identifier.',sum(query),sum(!query),og_note,length(excluded),sum(query&!nzchar(md$sample_id)))
writeLines(caption,paste0(stem,'_caption.txt'));capture.output(sessionInfo(),file='R_SESSION.txt')
