#!/usr/bin/env python3
"""
verify_tier_derivation.py — assert that a public tier is an exact redaction-view
of the PRIVATE source tree, using the project's own redaction logic.

This is the cheap parity check that replaces re-running the full pytest suite per
tier: if every file in the public tier equals redact(private_counterpart), the
public tier carries no behavioral difference from the source by construction.

Usage:
    verify_tier_derivation.py <private_tree> <public_tree> [--ext .py,.md,.json,...]

Exit 0 = every shared file matches redact(private). Non-zero = drift (investigate).

NOTE: redaction logic is imported from tools/redact_public_tier.py so there is a single
source of truth for the rule. (Previously this file inlined its own copy, which drifted:
it lacked the v9.7.97 AS-48 public-NP carve-out and so reported FALSE drift on every file
mentioning the public bacteriocin enterocin AS-48. Import, do not duplicate.)
"""
from __future__ import annotations

import os as _os, sys as _sys  # v9.7.407: resolve the tools-local emitter from any cwd
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from _console import emit  # noqa: E402
import argparse, os, sys
from pathlib import Path

# --- single source of truth: import the live redaction logic ----------------
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from redact_public_tier import redact_text as _redact_text, redact_py as _redact_py  # noqa: E402
from redact_public_tier import _is_keyed_registry, _redact_json_registry  # noqa: E402
from mamey.privacy_profile import PrivacyProfileError, PublicExportPolicy, load_public_export_policy  # noqa: E402

# Files that legitimately differ between tiers (build metadata) — never expected to match.
METADATA_SKIP = {"SOURCE_CHECKSUMS_SHA256.txt", "TIER_MANIFEST.txt",
                 "BUNDLE_FINGERPRINT.txt", "CHANGELOG.md",
                 # Regenerated by in-tier tests from the staged public tree, then passed through
                 # the documentation privacy transform and release audit a second time.
                 "docs/BUNDLE_CAPABILITIES.md", "TOOLS_INVENTORY.generated.md",
                 # v9.7.274: BUILD_STAMP.txt's `tier=` field is now set per tier (to match
                 # TIER_MANIFEST), so it legitimately differs from the source's tier=CODE.
                 "BUILD_STAMP.txt"}

# Directories the cut legitimately STRIPS from the public/code tier (make_public_tier.sh: strip_internal
# + the caches removed at stage-1). A private-tree file under one of these has no public counterpart BY
# DESIGN — it is not drift. Kept in sync with make_public_tier.sh so the verifier mirrors the cut; add a
# dir here whenever the cut learns to strip it (v9.7.382: _CANDIDATE_NOTES/ was added to strip_internal).
STRIP_DIR_PREFIXES = (
    "_CANDIDATE_NOTES/", "docs/internal/", "tools/internal/", "scripts/one-off/",
    "future_improvements/", "private/", "cohort/", "merged_cohort/", "data/",
    "release2_source_library/", "docs/legacy/", "offline_deps/",
    ".pytest_cache/", "__pycache__/", ".git/",
)

import re as _re
# BC2-VTD-01 (v9.7.396): the dynamic-run-dir check was `first.startswith("runs")` — a bare prefix
# match with no word-boundary, so ANY root-level file or directory whose name merely starts with
# the substring "runs" (e.g. "runsafe_check.py", "runsanalysis_helper.md" — ordinary, plausible
# names for a future root-level script or doc in an actively-developed project whose own .395
# CHANGELOG entry describes routine root-file churn) was wrongly classified as "stripped by
# design" and silently excluded from the whole redaction-parity comparison loop -- the exact same
# "silently narrows what actually gets checked" bug shape this file's own v9.7.374 fix (a few
# lines below) explicitly closed for files missing from the public tree entirely. Reproduced:
# _is_stripped("runsafe_check.py") returned True on pristine .395, though it is not a dynamic
# run-output directory at all. Require "runs" to be followed by a genuine boundary (end of
# string, or -/_/. before the rest of the name) so "runs", "runs-old", "runs_2026" still match
# but an unrelated root-level name merely starting with the same four letters does not.
_RUNS_DIR_RE = _re.compile(r"^runs($|[-_.])")


def _is_policy_stripped(rel: str, policy: PublicExportPolicy) -> bool:
    """Omissions the DECLARED export policy is responsible for, as opposed to the structural
    ones above. Kept separate so a reader can tell which of the two authorities excluded a path."""
    normalized = rel.replace(os.sep, "/").lstrip("./")
    directory_parts = normalized.split("/")[:-1]
    if any(part in policy.excluded_root_names for part in directory_parts):
        return True
    return any(normalized == item or normalized.startswith(item + "/")
               for item in policy.excluded_relative_paths)


def _is_stripped(rel: str, policy: PublicExportPolicy | None = None) -> bool:
    """Mirror the code/public cut's structural omissions.

    Root-level run directories are named dynamically (runs, runs-old, runs_2026, ...),
    so they cannot be represented safely as a single static path prefix.
    """
    # CODEX_392 rebase: the incoming patch restored `first.startswith("runs")` here, because it
    # was authored before BC2-VTD-01. Reapplying it verbatim would have silently reverted that
    # fix and re-excluded any root-level name merely beginning with "runs" from the whole
    # redaction-parity loop. The boundary regex is kept; only the policy term is added.
    policy = policy or load_public_export_policy()
    rel = rel.replace(os.sep, "/")
    if rel.startswith("./"):
        rel = rel[2:]
    first = rel.split("/", 1)[0]
    return (bool(_RUNS_DIR_RE.match(first))
            or _is_policy_stripped(rel, policy)
            or any(rel.startswith(p) for p in STRIP_DIR_PREFIXES))

def redact_text(t: str) -> str:
    return _redact_text(t, as_only=True)

def redact_py(text: str) -> str:
    return _redact_py(text, as_only=True)

def redact(path: str, text: str) -> str:
    if path.endswith(".py"):
        return text
    # keyed strain registries use the collision-safe JSON redactor (same as the cut) so the
    # parity check compares like with like — plain redact_text would collapse AS-keys and
    # false-positive against the correctly-redacted cut.
    if path.endswith(".json") and _is_keyed_registry(text):
        return _redact_json_registry(text, True)
    return redact_text(text)

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("private_tree")
    ap.add_argument("public_tree")
    ap.add_argument("--ext", default=".py,.md,.json,.csv,.txt,.cff,.sh,.yaml,.yml,.toml")
    ap.add_argument("--privacy-profile", default=None,
                    help="optional sapote_privacy_profile_v1 used by the public cut")
    args = ap.parse_args()
    try:
        policy = load_public_export_policy(args.privacy_profile)
    except PrivacyProfileError as exc:
        # Typed refusal on stderr. sys.stderr.write, not print(file=...), because the repo_health
        # ratchet counts print( calls by AST and cannot see the file= keyword — a diagnostic that
        # is already correctly routed would still read as new library debt.
        sys.stderr.write(f"FAIL: invalid privacy profile: {exc}\n")
        return 2
    exts = tuple(e if e.startswith(".") else "." + e for e in args.ext.split(","))

    tested = matched = mismatched = skipped = identity = 0
    mismatches = []
    missing_from_public = []
    for root, _, files in os.walk(args.private_tree):
        for fn in files:
            if not fn.endswith(exts): continue
            priv_p = os.path.join(root, fn)
            rel = os.path.relpath(priv_p, args.private_tree)
            relposix = "/" + rel.replace(os.sep, "/")
            # a file under a dir the cut strips is absent from the public tier BY DESIGN, not drift
            if _is_stripped(rel, policy):
                continue
            pub_p = os.path.join(args.public_tree, rel)
            if not os.path.exists(pub_p):
                # v9.7.374 (audit lane): pre-fix this silently `continue`d — a private file
                # completely ABSENT from the public tree was never counted as tested, matched,
                # mismatched, or skipped, and never appeared anywhere in the report. Live-
                # reproduced: a private-only .py file with no public counterpart produced a clean
                # "OK: public tier == redact(private source) for every shared content file." /
                # exit 0, even though "for every shared content file" silently narrowed to only
                # the files present in BOTH trees. A file dropped entirely is drift too (it is
                # either a legitimate metadata-class omission that belongs in METADATA_SKIP, or a
                # real cut-step failure) — this checker's whole purpose is asserting the public
                # tier IS an exact redaction-view of the private source, so a silently-omitted
                # file must be surfaced, not swallowed.
                missing_from_public.append(rel)
                continue
            if fn in METADATA_SKIP: skipped += 1; continue
            priv = open(priv_p, encoding="utf-8", errors="ignore").read()
            pub  = open(pub_p,  encoding="utf-8", errors="ignore").read()
            # tests/ and the synthetic-ID allowlist are deliberately NOT redacted
            # (they carry synthetic fixtures so the in-tier pytest gate stays passable).
            # Policy there is identity between tiers, not redaction-equality.
            if "/tests/" in relposix or fn == "test_synthetic_ids.txt":
                identity += 1
                if priv == pub:
                    matched += 1
                else:
                    mismatched += 1; mismatches.append(rel + "  (expected identical, unredacted)")
                continue
            tested += 1
            if redact(rel, priv) == pub:
                matched += 1
            else:
                mismatched += 1; mismatches.append(rel)

    emit(f"redaction-checked : {tested}", f"identity-checked  : {identity}  (tests/ + synthetic allowlist; not redacted by policy)", f"all checks passed : {matched}", f"metadata skipped  : {skipped}", f"MISMATCHES        : {mismatched}", sep="\n")
    for m in mismatches[:25]:
        emit("   DRIFT:", m)
    emit(f"MISSING_FROM_PUBLIC : {len(missing_from_public)}  (private file has no public counterpart at all)")
    for m in missing_from_public[:25]:
        emit("   MISSING:", m)
    if mismatched or missing_from_public:
        if missing_from_public:
            emit(f"\n{len(missing_from_public)} private file(s) have NO public-tier counterpart at all — "
                  "either add them to METADATA_SKIP if this is a legitimate build-metadata omission, "
                  "or investigate the cut step that dropped them.", file=sys.stderr)
        emit("\nFAIL: public tier is NOT an exact redaction-view of the private source.", file=sys.stderr)
        return 1
    emit("\nOK: public tier == redact(private source) for every shared content file.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
